== Chapter II.

[.chapter-synopsis]
* 1652+++.+++ George Fox`'s first visit to Swarthmore
* The tendency of his doctrine
* William Caton leaves school and becomes an inmate in the Fell family, as teacher and writer
* The divine love and refreshment prevalent amongst them
* Is moved to go into steeple-houses, markets, etc.
* Quits Swarthmore.

In the year 1652, about the middle of the fourth month,
was that faithful messenger and servant of the Most High, George Fox, cast among us,
who declared unto us the way of life and peace.
Of those in that family who believed his report, I was one,
who came finally to be affected with his doctrine;
though at the first I did as much admire at his nonconformity to our fashions, customs,
and salutations, as strangers at this day admire at our non-conformity to them;
yet something in me loved him, and owned his testimony.
I began to find in myself the truth of what he spoke;
for his doctrine tended very much to bring us to "`the light,
which Christ Jesus had enlightened us withal, which shined in our hearts,
and convinced us of sin and evil;`" and into love with that, and obedience to that,
he sought to bring us,
that thereby through the Son we might be brought into unity and covenant with the Lord.

In due time the witness of God was awakened in me,
whereby my sins came to be set in order before me;
and it brought judgment and condemnation upon me by reason of them: but I,
being as the wild heifer which is unaccustomed to the yoke, sought to get from under it,
as I often did, until I came to know something of the power of God,
which brought that wild nature in me, which was unaccustomed to the yoke,
into subjection.
And so good was the Lord unto me, that I had not long heard the Truth,
when I came to be a witness of the power of it in myself;
whereby the strong man in me was made to bow, and the keepers of the house to tremble.

At that time I had not left the school, but went with Judge Fell`'s son thereto;
and he being somewhat convinced of the same truth, and touched with the same power,
it was the easier and the better for me: howbeit, we were often wild, vain and wanton,
and sported ourselves in folly, to the extinguishing of the good oftentimes in ourselves.
But such was the love of God to me in those days,
that I was as surely pursued with judgment, as I was overtaken with folly.
Sometimes I would separate myself from the rest of my schoolfellows,
and get retired into some place,
where I might wait upon the Lord and ponder upon his marvellous works.
When I was thus retired, and in singleness of heart waited upon the Lord,
I received refreshment from him;
but when I was drawn aside through the provocation of my companion,
or the temptations of the wicked one in myself,
then was I troubled and disquieted in my heart.

In process of time my study became my burden;
for when I was so much in trouble through the condemnation that was upon me,
I was so much the more incapable of making themes, Latin verses, etc.,
neither could I well give to the master the trivial compliment of the hat,
for I was then convinced in my conscience of the vanity of it.
My special friend Margaret Fell, the judge`'s wife, taking notice of my condition,
was not willing to suffer me to go longer to the school than I was free,
but caused me to stay at home to teach her children,
and to go with her when she went abroad, and to write for her, etc.,
which was a happy time for me.
After I left the school,
I was much exercised in writing precious and wholesome things pertaining to the Truth;
whereby I came to have good opportunities to be conversant with Friends,
in whom the life of righteousness began to bud and spring forth,
and who grew in love and unity, with which my soul was exceedingly affected;
and I desired very much to be one with them in it, that I might share with them therein,
for my soul was delighted with it and in it,
far beyond the pleasures and delights of this transitory world.

When I was about seventeen years of age,
the power of the Lord God did work mightily and effectually in me, purging, cleansing,
and sanctifying me;
and then I began to see something of the
gloriousness of the ministration of condemnation,
and of the goodness of the Word of life,
which was become "`as a fire in my bones,`" and "`as a sword and hammer in my heart.`"
I began to be broken, melted and overcome with the love of God,
which sprang up in my heart,
and with the divine and precious promises that were confirmed to my soul.
Oh! the preciousness and excellency of that day!
Oh! the glory and the blessedness of that day! how, or wherewith shall I demonstrate it?
or by what means shall I explain it, that generations to come,
and they that are yet unborn, might understand it, and give glory unto the Lord Jehovah?

Oh! the love which in that day abounded among us,
especially in that family! and the freshness of the power of the Lord God,
which then was amongst us; and the zeal for Him and his truth,
the comfort and refreshment which we had from his presence,--
the nearness and dearness that were amongst us one towards
another,--the openings and revelations which we then had!
I confess I find myself insufficient to declare these things to the utmost;
neither do I now intend to go about to describe them particularly;
for then I might make a larger volume by much, than now I am intending; but,
my heart is affected with the remembrance of them at this day.

In those days meetings were exceedingly precious to us,
insomuch that some few of us did commonly spend
some time every night in waiting upon the Lord;
yea, often after the rest of the family were gone to bed: and,
oh! the comfort and refreshment which we had together,
and the benefit which we reaped thereby, how shall I declare it?
For if we had suffered loss in the day-time,
when we had been abroad about our business or the like,
then we came in a great measure thus to be restored again, through the love, power,
and mercy of our God, which abounded very much unto us.
Howbeit, sometimes I was deprived of that sweet society, when my heart was with them,
through my going to my bed so early with the judge`'s son, with whom I then lodged.
For a season he was tender and hopeful; but afterwards meeting with many temptations,
his heart was drawn aside from the truth,
and his mind ran after the delights and pleasures of this present world.

When he was removed to another school, we came to be separated,
which was at that time no disadvantage to me in one respect,
though looked upon by some to be a disadvantage as to my outward preferment.
But in that day I could have chosen much rather
to do any kind of labour pertaining to the house,
with the servants that were in the truth,
than to enjoy the delights of this world with this son, or any one else, for a season.
For my delight was not then, so much as it had been, in the vain, perishing,
and transitory things of the world, but in the Lord, in his mercy and loving kindness,
and to be with his people;
for the sake of whose company I could have exposed myself to some pretty hard employment.
Neither was it then too contemptible for me to become as Amos, a keeper of cattle,
or as Elisha, to follow the plough;
for indeed in those days I did enjoy and possess
that which made all things easy and light to me.
And oh! the abundance of living refreshment,
which I received from the Lord! it is hard for
me to utter or declare the same to the utmost.
I was often overcome with the love of my Father,
which did exceedingly break and ravish my heart,
and I know it was so with others of that family; and of the overflowings thereof,
we communicated one to another, to the comforting and refreshing one of another.
We were willing to sympathize and bear one with another, to be helpful one unto another,
and in true and tender love to watch one over another.
And, oh! the love, mercy, and power of God, which abounded to us, through us,
and among us, who shall declare it?
Hence came that worthy family to be so renowned in the nation,
the fame of which spread much among Friends:
and the power and presence of the Lord being so much there with us,
it was as a means to induce many, even from afar, to come thither;
so that at one time there would be Friends out five or six counties:
all which tended to augment my refreshment.

By reason of my much writing,
it came to pass that I especially was much conversant with them,
and thereby I had a privilege beyond others of my fellow servants.
I was frequently with dear George Fox, who, as a tenderhearted father,
after he had begotten me through the gospel, sought to nurture me up in all wisdom,
faithfulness, and righteousness, to the glory and praise of my heavenly Father.
And on the other hand I was cherished, and encouraged in the way of life,
by my entirely beloved friend Margaret Fell,
who as a tender-hearted nursing mother cared for me,
and was as tender of me as if I had been one of her own children: the kindness,
the respect and friendship, which she showed me, ought never to be forgotten by me.

When I had thus plentifully reaped of the mercy of the Most High,
and his power had wrought so effectually in me, to the redeeming of my soul from death,
then did his Word of life begin to grow powerful in me:
and seeing the darkness and ignorance so great, in which people were involved,
my spirit was stirred within me, and came to be tilled with love to their souls,
and with zeal for God and his truth.
About that time I began to know the motion of his power and the command of his Spirit;
by which I came to be moved to go to the places of public worship,
to declare against the deceit of the priests, and the sins of the people,
and to warn all to repent: for I testified to them that the day of the Lord was coming.
But oh! the weakness,
the fear and trembling in which I went upon this message,--who shall declare it?
and how did I plead with the Lord concerning this matter:
for I looked upon my own weakness and insufficiency,
and how unfit I was in my own apprehension, to encounter with gainsayers,
who I knew would also despise my youth.
Howbeit,
whatever I alleged by way of reasoning against the Lord concerning this weighty matter,
I could not be excused; but I must go, and declare what he should give me to speak;
and his promise was, he would be with me.

When I saw it must be so, I put on courage in the name of the Lord;
and having faith in him, which stood in his power, I next gave up to his will,
and went in obedience to his motion.
When I came to the place, behold, the consultations which before I had had, were gone,
and the fear of man was departed from me; and strength, and courage, and boldness,
and utterance were given me, so that I became, through him that strengthened me,
rather as a potent man than as a stripling,
and that even in the face of the congregations.

Howbeit, my testimony was by many little regarded,
neither did they lay to heart what I declared among them.
Some fell upon me, and did much abuse me; others pitied me and were much troubled for me;
and sometimes they were much divided among themselves, for some were for me,
and others against me.
But in the midst of them the Lord was with me, and his mighty power did preserve me;
and when I had cleared my conscience among them,
I returned in much peace and joy in the Holy Ghost, for my reward was with me.

After the Lord had fitted me for his work as aforesaid,
I was much exercised in going to steeple-houses,
insomuch that there seldom passed a first-day of the week, but I was at one or another;
and I was also often in markets, where I was moved to declare God`'s eternal truth,
of which through his infinite mercy I was become a witness.
And though when I went to such places as aforesaid,
I seldom knew what I should say till I came there;
yet behold when I was to speak I never wanted words or utterance,
to declare that which the Lord gave me to publish;
but oftentimes on the contrary I had fulness to my great admiration.
And the beating, buffeting, stocking, stoning, with the many reproaches,
which I went through in those days, were little to me; nay,
not to be compared to the refreshment which I had through the enjoyment of the life,
power, and love, which the Father had revealed in me,
and by which I was carried through them and over them all.
By how much the more the Lord tried me in those days,
by so much the more I came to experience his loving kindness to me.

After the Lord came to honour me with bearing his name,
and accounted me worthy to bear my testimony, both in public and in private,
to his eternal truth, I had much favour and respect from and among his people,
whose love abounded much to me; and I being sensible thereof,
was very much supported and strengthened thereby,
in that service which God appointed for me, and called me unto.
When such service was over I returned again to the place of my residence,
where I was diligent in my employment, until the Lord ordered me to other service again,
either to meetings abroad on the first-days of the week, or else to steeple-houses:
and the Lord was with me, and his word of life did often pass powerfully through me,
and never did I go about any service for the Lord, in which I was faithful,
but I had always my reward with me.

When I returned again unto that honourable family, the place of my abode,
(I mean Judge Fell`'s at Swarthmore,
in Lancashire,) then was our refreshment very great together in the Lord,
and with rejoicing did we speak together of his wonderful works,
which were very marvellous in our eyes.
And after I had had many glorious days there,
and seen many of the wonderful works of the Lord, in the fulness of time,
according to the will of God I was called out from among them,
the Lord having other service for me elsewhere.
When it was the will of the Lord that I should go, the judge was much against it,
being then very unwilling to part with me; but his dear wife,
who could not well give me up before,
was then made willing freely to resign me to the will of the Lord,
especially upon so honourable an account; for I left them not to go to serve other men,
but to publish the name of the Lord, and to declare his eternal truth abroad.
