== Chapter III.

[.chapter-synopsis]
* 1654+++.+++ Leaving Swarthmore he travels southward into Warwickshire and to Norwich, and afterwards to London
* He and the brethren have great service in that city, etc.

It was in the year 1654, in the eleventh month, when I was about eighteen years of age,
that I took my leave of that renowned family at Swarthmore.
But, oh! the tears that were shed among us at our parting;--the
prayers and intercessions that were made to the Lord;
and what deep impression our parting had upon our hearts, who can declare the same.
So exceedingly were we united and bound up together,
that it was very hard for us to part one with another.
Howbeit, when we considered upon what account it was,
and that notwithstanding our parting, we should enjoy one another in the Lord,
then could we give up to the will of the Lord so much the better in the thing.
Therefore according to the will of the Lord, in his name and power,
I set my face southward; and visited Friends in Lancashire,
and in some parts of Yorkshire and Derbyshire,
which counties I passed through into Warwickshire, to a place called Badgley;
where I met with many of the brethren, who did dearly own the power,
and the motion of it, by which I was drawn forth into that glorious work.

Being very sweetly refreshed together, and confirmed in the faith and power of God,
and encouraged to go on in that glorious and honourable service, I took my leave of them,
and went on in the name and power of the Lord towards Norwich in Norfolk,
being accompanied by another Friend; and coming to Wellingborough in Northamptonshire,
we found several there newly convinced of the Lord`'s truth,
with whom we were much refreshed.
And being there the first-day of the week, it was upon me to go to their steeple-house,
where I had some liberty (and but little) to declare the everlasting truth of God.

After that I returned to the meeting of Friends,
where the power and presence of the Lord God were with us; so that a very sweet,
comfortable, and refreshing meeting we had.
I and my companion were apprehended, and kept that night in custody; but the next day,
as Providence ordered it, while the priest and some with him, as we were informed,
were gone to get a warrant to bring us before a justice,
we were by a certain officer released.

After that we travelled towards Cambridge,
where we had a very good opportunity to visit Friends; which having done,
we passed on our journey towards Norwich.
It being in the depth of winter, and we travelling altogether on foot,
it was something hard to the outward man; but the Lord was with us,
and his mighty power upheld us, and carried us through all,
and through mercy we got well to Norwich;
where there were several of our north country Friends in prison, whom we visited,
and with whom we were sweetly refreshed.

In this city we had a very large meeting, to which many people resorted;
and the Lord was with me,
and gave me a mouth and wisdom freely and powerfully to declare his living truth:
at that time we were in much jeopardy of being taken,
but the Lord preserved us out of the hands of unreasonable men.
At that city my companion left me, and returned towards the north;
and after I had visited Friends and the brethren there, I went into the country,
and had very good service for the Lord; and in a short time after I went to London,
where I was very kindly received by Friends, and we were refreshed together in the Lord.

Not long after,
came several of the brethren to the city out of the north and other parts;
and the mighty power of the Lord God was with us, and very much we were exercised,
sometimes in steeple-houses, and sometimes in the meetings of Separatists.
Upon one first-day I was at two of their steeple-houses in the forepart of the day,
and at one of them I had large liberty to speak.
In the afternoon I was at a meeting of Professors,
where there were six that spoke one after another and I had liberty to speak
freely among them without opposition or contradiction from any of them,
and afterwards I departed in peace.

About that time, the word of the Lord grew mightily in that city,
and many were added to the faith; and many steeple-houses,
and most of the meetings in the city were visited by some of the brethren;
for at one time there were ten or twelve of the ministering brethren in the city;
most of which came out of the north, even plain, honest, upright men,
such as the Lord was pleased to make use of in that day;
and very diligent we were in his work night and day,
labouring faithfully so much as in us lay, to exalt his name over all,
and to make his truth and salvation known unto all.

Many meetings we had about that time in the city,
and I began to experience much of the faithfulness of the Lord to me,
who furnished me according to necessity,
and was pleased to give that which was suitable to the condition of the people,
unto whom I was to communicate it.

About that time, I met with my dear brother John Stubbs,
who was also come up to London out of the north;
and though at that time we had little outward knowledge one of another,
yet Providence did so order it, that we became companions and fellow travellers together.
It was upon us to go into the country, partly towards Uxbridge;
and at a certain place within a few miles of Uxbridge,
Ave had very good service both in the steeple-house, and also at a meeting,
which was ordered upon our coming to that place; and the Lord was with us,
in whom we were strong, and our word powerful, though in our own eye we were weak,
and contemptible in the eyes of many.
The priest being moved with envy, stirred up the people against us,
so that through his means we were apprehended and carried before a justice;
but he being a moderate man, reasoned moderately with us, and perceiving our innocency,
discharged us.
Afterwards we returned to London again with joy and rejoicing,
when we saw how the Lord had been with us, and how eminently he had appeared,
through us weak and contemptible vessels;
which we made known to the brethren at our return, who, when they understood it,
rejoiced with us.
