== Chapter V.

* 1655+++.+++ He visits Calais in France
* Returns to Dover
* Travels to Yarmouth, and afterwards into the North
* With John Stubbs sails to Holland
* Their labours in that country
* Returns to England.

Upon the 12th of the fourth month, 1655, it was upon me to go over to Calais, in France,
which accordingly I did from Dover.
When I came there, and saw the place so much given to idolatry,
my spirit was very much burdened and pressed within me:
and in the power of the Lord I went to their high place of worship,
where some were worshipping before their dumb idols: and I walked through by them,
but could not well ease myself with words to them, because they could not understand me,
neither could I then understand their language;
but the Lord afterwards made way for me to ease my spirit,
and to clear my conscience among some of them.
For after I had been some little time in the place,
it came to be known to some of the chief of the city, who desired to see me,
and to speak with me, and some of them came down in person to the quay to look for me,
and understanding I was aboard, I was called ashore,
and was afterwards conveyed through private places, for fear of the rude multitude,
as he told me that was appointed to convey me, to a great house,
where several of the great ones were gathered together, to see me, hear me,
and to speak with me,
so that I had a very gallant opportunity to declare the truth among them.
A certain Scotch lord, so called, was the interpreter;
and precious dominion the Lord was pleased to give me over their vain,
frothy minds and spirits, which were very much addicted to lightness and vanity.
When I had had this opportunity to clear my conscience among them,
they suffered me to depart in peace.
And soon after I was clear, and free to return again for England, which I did,
and found my dear companion John Stubbs, at Dover.

About that time it was upon John Stubbs to go to Holland,
and I was made very free in the Lord to accompany him.
We had some good service afterwards in the country, in our return towards Gravesend;
and from thence we went to Colchester, and so to Yarmouth in Norfolk.
As to the outward we were poor and feeble, yet full of power and strong in the Lord,
and were very provident and sparing in our expenses,
of which I could say more than here I am free to insert;
yet nevertheless the Lord did enable us to travel day after day,
and many a mile upon a day, notwithstanding our keeping our bodies so much under.
Neither did we in those days want for money, of which we might have had plenty given us;
but our hearts being clear and free from coveting that, as the Lord well knows,
we kept ourselves clear and free of it; for as we had received freely,
so we were as willing to give freely, and the little we had,
the Lord did sanctify and bless to us, and our reward we had always with us,
in whatsoever place or condition we were.

After we came to Yarmouth,
we waited there and in the country thereabouts the most
part of three weeks for a passage for Holland;
and finally an opportunity of a ship seemed to present, as also of wind;
so we got aboard, though not without some difficulty in the roads:
but presently after the master came aboard, and perceiving what we were,
he would not carry us, but forced us ashore again; which disappointment,
after we had waited so long, was no small trial to us.

When we saw there was little likelihood of our getting passage from thence for Holland,
we determined to go for the north; and after we had waited some time longer there,
we got passage for Sunderland, having no small weight upon us,
which was the heavier because it was reported in the nation among Friends,
that we were gone over sea.

When we came into the north,
I had much desire in me to go to see my dear and near
relations in the Lord at Swarthmore and thereabouts,
and Providence did so order it that I had an opportunity.
Oh! the refreshment which we had at our meeting, and during the time I stayed among them,
it would be hard for me to declare it to the utmost.
Dear Margaret Fell, who had been as a tender-hearted, nursing mother to me,
was refreshed to hear how the Lord had been with me, how he had blessed my labours,
and prospered his work in my hand; for all which mercies, together with many more,
we returned unto the Lord his praise, his due,
and with joyful hearts offered unto him the sacrifice of praise and thanksgiving.

When I had stayed some little time there, in which I was refreshed both in soul and body,
it was upon me to return again,
to endeavour to accomplish the aforesaid journey to Holland;
and when the time of my departure was come,
I took my leave of them with much brokenness of heart, in which I also left them;
and visiting other Friends, I returned again into the bishopric,
where I had left my dear companion.
Afterwards we had some precious meetings in those parts,
which together with those we had had before, were of no small service:
and being pretty clear of those parts, we sought again an opportunity for Holland.

Coming to Shields, we heard of a ship that was intended for Flanders, which,
though it was in the king of Spain`'s dominions, and pretty wide from Holland,
yet we were willing to go along with her, hoping to get passage from thence;
so going aboard of her, we got finally through mercy to Yarmouth Roads again,
where we found a ship intended for Flushing in Zealand,
which being nearer to Holland than Flanders, we embarked in her.
Through the mercy of the Lord, we arrived well at Flushing;
where we came among a people of a strange language,
among whom we had been but a little time,
when our spirits were stirred within us by the power of the Lord;
through which we were moved to proclaim his mighty day, and to publish his eternal truth,
in and through their streets, whether they could understand or no; which we did,
and his power and presence were with us.
At that time no man laid hands upon us; so after we had unburdened our spirits,
by easing them of the weight that was upon them, through obeying the Lord,
we returned to our lodging again.

When the first-day of the week came,
it was upon us to go to the congregation of the English and Scotch, which we did;
and many gazed upon us and wondered at us, because of our non-conformity to them.
But after we began to speak, they were much stirred, some with fury and rage,
and others with admiration; but withal, they would not suffer us to speak much,
but hurried us out with great indignation, and some violence was offered to us:
howbeit the Lord preserved us,
so that we received but little harm from them,--blessed be his name forevermore!

The same day we went to another great city called Middleburgh,
and got thither before their afternoon`'s devotion was ended.
When we came there,
it was upon us to go to the meeting place where the English and Scotch did meet,
where we waited until the priest had done; afterwards one of us began to speak,
but the priest would not suffer us, imagining at first, before he understood us well,
that we had come a begging.
But when he perceived the contrary, he and others were more against us,
and some especially were very violent, and did beat me much;
and indeed had not the Lord been with us, and preserved us through his mighty power,
they might have done us much mischief; but blessed be the Lord,
he was our keeper and preserver.

After that, the priest sent for us to his house, and reasoned awhile with us;
but he was of such a lofty and ambitious spirit, as many of that generation are,
that the truth could have little entrance in him, or entertainment from him.
After we had had other good service in the city, and were become pretty clear of it,
we embarked for Rotterdam in Holland; where,
after some difficulty and hardship sustained, we arrived through the mercy of the Lord;
but did not know the face of any.
When we had been some few days in the city, it was known to several,
and after some time we got a meeting at an English merchant`'s house,
to which many merchants came, both Dutch and English.
We suffered for want of a good interpreter;
for he that interpreted for us not being true and faithful,
to interpret our words as we spoke them, but sometimes otherwise,
the hearers or some of them, came rather to be incensed against us,
than to be won or gained to the truth; howbeit, the witness of God in some,
answered to the truth of our testimony.
As there had been no Friend before to declare the truth among them in that city,
it was looked upon as so much the stranger thing,
and we were so much the more wondered at; but in due time,
when we had cleared our consciences,
and borne a faithful testimony to God`'s truth in that place,
we departed thence and returned again for Zealand, where we took shipping for England.

After we had waited some time for the wind, we had an opportunity of sailing,
but met with a very sore storm at sea; howbeit the Lord preserved us,
and we got well to Burlington (Bridlington), in Yorkshire,
but were not permitted to go into the town, because we were come from Holland,
where it was said the sickness then was; nevertheless we saw our Friends,
and were refreshed in seeing one another.
Soon after we set sail again, and when we came near Hartlepool,
the wind blowing very hard, we lost our foremast, and were in some apparent danger;
but the Lord was pleased to preserve us then also,
and to assuage the violence of the boisterous waves through his mighty power,
in which we put our confidence.
And when through mercy we were gotten well ashore,
we went up into the country among Friends,
with whom we were more than a little refreshed in the Lord.
After I had had several meetings in the bishopric +++[+++Durham,+++]+++
I went again into Lancashire, and coming to Swarthmore,
I was received with joy again in the Lord, in whom our refreshment was great,
and a very precious time we had afterwards together,
whereby my very life was much revived; and therefore did my soul magnify the Lord,
with the rest of his lambs and babes in that place.
