== Chapter VI.

[.chapter-synopsis]
* 1655+++.+++ Visits Scotland, passing through Northumberland
* Has good service for the Lord at Edinburgh and Glasgow
* Returns to Swarthmore, and proceeds to Cheshire.

It was not long after this, that I took my leave of that blessed family,
for I was to go for Scotland, towards which nation we had felt some drawings,
before we were clear of that service beyond the sea.
Having taken my leave in abundance of love of my dearly beloved friends at Swarthmore,
I went through Westmoreland, and had some good meetings among Friends there,
which were of good service.
Upon the 12th of the ninth month, 1655, I went towards the bishoprick,
in order to go into Scotland.
When I came into the bishoprick, I met with my dear companion John Stubbs again;
and when we had visited the brethren and Friends in those parts,
and had been truly refreshed together in the Lord,
we went afterwards into Northumberland; in some parts of which we had very good service,
especially in the country about Morpasse +++[+++Morpeth?]

About the beginning of the tenth month, 1655, we were at Berwick;
and upon the market day, it was upon us to go into their market,
where we had some good service.
On first-day following, I was moved to go into their great assembly,
where none of our Friends had been,
but such as had been imprisoned and afterwards put out of the town.
Nevertheless, I was not therefore to be discouraged,
but went in boldly in the name and power of the Lord; and when the priest had done,
I stood up upon a stall, but none seemed to make such haste to get away as the priest;
however, my mouth was opened in much power,
and the Lord was pleased to give me courage and boldness,
and indifferently good liberty I had to declare the truth.
When I had done, the mayor met me at the door, and took me by the hand,
and delivered me to the sergeants;
but afterwards I was brought before the mayor and magistrates,
and further examined by them,
who finally ordered that I should be turned out of the town, which also came to pass.
In the afternoon I was at a steeple-house in the country, where I spoke to the priest;
but he was furious, and called me madman and bid the people have me to the stocks,
and bind me hand and foot, with more such like expressions;
but none of the people would obey him, but gathered generally about me,
and were pretty willing to hear the truth declared, though they were a sottish,
ignorant people.
Afterwards I could not well get any lodging among them for my money;
and when I was wandering up and down, being destitute of a place to lay my head,
or to rest and refresh myself in, there came a man out of Berwick to me,
and I went along with him.
The guard suffered me to pass very freely into the town again,
where I met with my dear companion John Stubbs,
who had also been in great service that day; in the forenoon among the Baptists,
and in the afternoon he did supply the meeting which we had appointed;
so that day we had good service, and stayed afterwards some few days in that town,
and had another meeting or two there.

We travelled from thence into Scotland, towards Edinburgh;
and though our travails were great, and our sufferings many,
both in the inward and outward man, yet the Lord by his mighty power supported us,
and carried us through them all.
And that which made them the easier to us,
and made us the more capable to bear with them,
was the extraordinary love and unity in which the Lord preserved us;
insomuch that I do believe scarcely any of the brethren
who travelled abroad upon the same honourable account,
ever agreed better than we did, or were more mutual in their service,
and in other things incident to travellers, than we;
therefore were our travels and sufferings so much the more easy to us,
through him that blessed us,
and with the right hand of his righteousness supported us;--to whom be glory,
honour and dominion forever and ever!

When we came to Edinburgh, we found things somewhat out of order there,
through the unfaithfulness of some that were convinced of the truth,
but who did not order their conversation aright,
neither did they live as became the gospel; which we endeavoured to rectify among them,
as much as was possible; and the word of the Lord was effectual through us among them,
to bring them into better order.

After we had been some time together in that city,
it was upon my dear brother to go to some other places, as to Burnt Island, Ayr, etc.,
and afterwards to return to England again: so we parted in the fulness of endeared love,
with much brokenness of heart.
I stayed several weeks in that city, +++[+++Edinburgh,]
being accompanied by another dear brother, John Slee by name:
and many good meetings we had in the city, especially upon the Castlehill,
where many hundreds heard the truth of God in much power and plainness;
and often was the witness of God reached, and many were made to confess unto the truth;
so that we had extraordinary good service for the Lord.
We did not only keep our meetings upon the aforesaid public place,
but also we often had meetings at William Osborne`'s,
who formerly had been a Lieutenant-Colonel,
but was then become very zealous for the Lord`'s truth.
Upon one time especially,
it was upon me to go to their high place of worship,--
the chiefest in the city--which accordingly I did;
and after the priest had done, I spoke to the people, but was not suffered to speak much,
until I was carried out with the press of the multitude,
which was indeed extraordinarily great.
When I came out in the street,
there was a guard of soldiers set in readiness to secure me from the multitude,
and to conduct me to the place where I desired to be,
which they did with their drawn swords;
and after that I went in peace to the meeting of Friends.

I was also about that time with General Monk, so called, who was seemingly moderate,
and did hear me, and received such papers from me as I had to deliver to him.
I was also at Stirling; and at my going into the city, was carried to the main guard,
and from thence I was sent to the governor, who at first was high with me;
but when I had spoken a little to him, and had given him something to read,
he became more moderate.
I went from his house to the English chaplain`'s,
who was very moderate and kind in his way towards me.
After I had had good service among them, I went to Glasgow, another great city;
and it was upon me to go to their great cathedral,
where three congregations did meet at once; and after they had all done,
I had some liberty to speak to the multitude in the yard,
for the rude people were kept very much under by the English soldiers,
who were pretty moderate towards me, so that I had very good service in that city.

I was at a place called Douglas, where I had good service,
both in the steeple-house and elsewhere;
but the priest caused me to be turned out of my lodging,
and did what he could to hinder me from having any entertainment in the town;
but some that lived a little from the town, were willing to receive me into their house.

Thus after I had had such good service both in the city of Edinburgh,
and at the places afore-mentioned, I was pretty free to return again to England,
which I did.

When I came back to England,
I visited Friends both in Northumberland and in the bishoprick, +++[+++Durham]
and had some good service among them, especially in the bishoprick;
and afterwards I visited Friends again in Westmoreland,
and in due time got well back to Swarthmore, where I was received as formerly,
even in the fulness of dear and precious love.
I found the power and the presence of the Lord with them as formerly,
and therefore was our refreshment together again as it was wont to be, I could truly say,
it was good to be there: but the Lord having much service for me abroad,
I could not stay long before I was constrained to
travel again in the work and service of the Lord,
About the middle of the first month, anno 1656, it was upon me, and another dear brother,
William Simpson, to go down into Lancashire and Cheshire, etc, to visit Friends,
which accordingly we did.
Many precious and serviceable meetings we had,
and the Lord`'s heavenly power and presence were much with us,
and very good service we had both at Warrington and Manchester;
and I was at the great Independent congregation at Stopard, +++[+++Stockport?]
but Eaton, their pastor, caused them presently to take me away,
so that I had very little liberty among them.
Afterwards I went to the meeting at Manchester,
and my companion was moved to go to the steeple-house, but had little liberty to speak,
for he was taken thence, and was turned out of the town,
as he had been twice the day before: but that night he came in again,
and we had a good meeting in the town, as I had had the night before at Stopard.
The next day many people followed us, through William`'s speaking, at the end of the town,
and there I had a favourable opportunity to declare God`'s truth among them;
which they heard with moderation and attention.
Upon the third-day following, we had a meeting at a place called Sunderland,
and upon the fourth-day another meeting four miles from thence, and on first-day,
we had a good general meeting within four miles of Northwich; yea,
night and day we laboured in the work and vineyard of our heavenly Father,
and our reward was with us.

We were put in prison at a place called Congleton in Cheshire;
and remained there some few days, when Providence did so order it,
that we were again released.
Time would fail me to relate particularly the good
service which we had at that time in Cheshire,
Lancashire, and at Leek in Staffordshire; sometimes in steeple-houses,
sometimes in streets and markets, and night and day frequently in meetings.
In due time we were made free in the Lord to return again,
after we had spent several weeks as aforesaid; and always when I returned to Swarthmore,
it was to me a place of refreshment.
