== Chapter IX.

1656--Sails for Holland--Visits Amsterdam and Rotterdam--His
service at both places--Is imprisoned at Middleburgh,
and conveyed on board of a ship of war for England--Travels into the South of England,
returns to London (1656-7)--Proceeds again to Holland.

About the beginning of the seventh month 1656, being at London,
with several of the brethren,
we had at that time much disturbance in our meetings in
the city by some troublesome and unruly spirits,
who were gone from the truth into extremes; and though we suffered by them,
yet we were refreshed together in the Lord, and one in another.

About that time it was upon me to go over for Holland,
unto which I was given up in the will of the Lord.
I was then but weak in body,
having gotten a surfeit through heats and colds in my travels, as it was judged.
Nevertheless I was in readiness, though in that weak condition,
to take the first opportunity; and very much I desired to have a companion along with me,
if Providence had so ordered it: howbeit, I went finally alone;
and met with some wicked and uncivil men in the same vessel in which I went over;
some of whom in their jollity abused me: but before we got over to Holland,
we had a pretty sore storm, and to outward appearance were in much danger.
At that time great was the fear and anguish that came upon those that were so wicked:
and even then the Lord raised me up, in whom my faith and confidence was.
It was upon me to speak to them in their distress,
and then the witness of God was near and ready to answer to the truth of what I spoke:
and the goodness and mercy of the Lord to me in that storm were very great;
through whose hand we were preserved, and finally, through his mercy,
brought well to our desired haven; blessed and magnified be his name for ever and ever.

When I landed at Dort, I do not know that I could speak three words of their language,
and so was much pressed in spirit, and sorely laden with the weight of iniquity,
which fell upon me; and seeing I wanted an interpreter,
therefore was my burthen the greater.
From Dort I sailed to Rotterdam, where I found some few that had heard the truth,
and who in some measure received it; howbeit, I stayed not long there,
for my drawings were to Amsterdam.
Through the good hand of the Lord I got well thither, where John Stubbs and William Ames,
my dear brethren, had been before with another Friend;
and very good service they had had among the professors there.
Some had received their testimony and the truth in the love of it;
and such with gladness and joy of heart received me.
And the Lord made my service effectual among them for
establishing and confirming them in that living truth,
which they had heard and believed.
There were some among them that could understand me,
and interpret that which I spoke to the rest; so that I had very good service among them,
for that little time I stayed, which was not long,
till it was upon me to return to Rotterdam.
In the mean time, a young man came over from England, who went with me,
and could understand both English and Dutch.
When I was at Rotterdam he left me for a while; and in the meantime,
I was much straitened for want of an interpreter;
but there being one that could speak some Latin,
I spoke some time in that language to him, and he interpreted it to the rest.
But my sufferings were exceedingly great in that country, in divers respects;
and they were augmented through some forward and unruly spirits that were convinced,
but who run out into extremes both in words and writing; whereby both the truth,
and they that lived in it, came to suffer much: for my part,
I had fainted through weakness and sufferings,
had not the Lord by his mighty power upheld and preserved me.

At that time few or none of the priest`'s proselytes came to our meetings,
but several high conceited professors, both at Amsterdam and Rotterdam attended,
and several of them were more apt to take upon them to teach others,
than to receive instruction themselves.

I was also at the Jews`' Synagogue at Amsterdam upon one of their Sabbath days;
and staying most of the time of their worship, I beheld the manner of it,
which was very strange in divers respects;
neither would they admit of any dispute in their Synagogue;
but after their worship was ended,
another Friend and I had some pretty good
service with some of them in one of their houses:
they are a very hard, obstinate, and conceited people in their way.
When I had stayed some time at Rotterdam, it was upon me to go to Zealand,
which accordingly I did, about the latter end of the eighth month 1656,
and the aforesaid young man went along with me.
And when we had been some days at Middleburgh,
he went to some of their meeting places in that city, and was apprehended;
which I understanding, went to visit him, and they, perceiving that I was his companion,
secured me also.
Afterwards we were examined very late in the night,
and after our examination we had three or four soldiers to guard us,
and a place appointed for us where we might lie.
But quickly after we were laid down, we were called up again in great haste,
and were carried from thence to the prison, about the eleventh or twelfth hour at night,
and put in two distinct places, which caused my sufferings to be the greater,
and the more, because I could speak little or none of their language.
There I remained some days, being weak in body, but in process of time,
we were brought before the council, and were severally examined,
but returned to prison again.

It seems they ordered (by what followed,) that we should be sent for England;
for soon after, a coach-wagon was brought to the door, to carry us to the water-side,
and several soldiers were also provided to guard us.
For the city seemed to be in an uproar, and the rude multitude raged exceedingly,
as if they would have torn us to pieces; but the Lord was with us,
who was our chief keeper, though there were some in the wagon with us,
and some that went on foot along by the wagon.

According to their order, they brought us on board of a ship of war,
where we were kept prisoners, near upon two weeks, being confined to an open, cold room;
and the men were so hard-hearted towards us,
that they would not allow us so much as a bit of sailcloth to lie under us, or above us:
thus for the most part of that time we lay upon the bare boards in very cold,
stormy weather, so that our sufferings were great both in the inward and outward man.

But, how is the goodness and mercy of the Lord to be admired, for even then,
while I was in prison, and so hardly used, my strength grew much,
and I recovered my health, in a great measure again,
even to my own and others`' admiration;
and thereby I came to have further experience of the goodness and mercy of our God,
for which my soul hath cause to bless and magnify his name for ever.

About the middle of the ninth month 1656, through mercy, we got well to England,
and about the same time came up to London.
We had extraordinary pain in our feet after we came to lie in warm beds,
having lain so long in cold weather in our stockings and shoes:
but meeting with many of the brethren there, my refreshment was great among them,
and in that good service which I had in the city.

When I had been about two weeks in the city, it was upon me to go down into the country;
and when I was travelling alone in Surrey, near Ryegate, a wicked,
murderous fellow came out of a house,
and fell upon me as if he would forthwith have murdered me;
but the Lord delivered me out of his hands,
and afterwards I went to the meeting of Friends that day.
I had good service in Sussex, especially among a people that were called Seekers,
who were mostly convinced, not far from Lewes.
I was also at Steyning, Arundel, Chichester, Portsmouth and Southampton,
at all which places I had good service for the Lord; as also at other places,
both in Hampshire, Sussex, Surrey, and Kent.
I had a meeting at the east side of Sussex,
where there had never been any Friends before;
and the rude multitude came with their drum, marching up to the house,
like men ready for battle, in a desperate manner,
as if they would have pulled the house down over our heads.
I was moved to go out to them, and asked them what they wanted; they said Quakers;
I told them I was one.
And it was upon me to speak in much plainness to them, which I did, and in much power;
and presently their countenance fell, and fear surprised them,
and with shame and confusion they withdrew, not having power to harm any of us,
blessed be the Lord; who in those days did eminently appear for us,
as he hath often done since,
therefore have we cause to put our confidence in him to the end.
About that time I had much good service for the Lord in those parts,
and when I was free of the same I returned again to London.

I had not stayed long there, when it was upon me to return again for Holland;
although I had some very good service in London, and in some part of Surrey,
before I was perfectly clear and ready to take shipping;
for about that time there was an effectual door open in and about the city,
and many of the brethren were there, and a very precious opportunity we had together,
to our refreshment in the Lord.

In due time way was made for my going over, and in the fulness of dear and precious love,
I took my leave of Friends and the brethren at London,
and through mercy arrived well at Rotterdam; and understanding there that William Ames,
a dear brother, was at Utrecht, I hastened thither,
where I found him in good service for the Lord, both to his and my refreshment.
Entering into discourse with him,
I understood that he had been in prison at Amsterdam with another Friend,
and that they were turned out of the city, etc.

Nevertheless, according as it was upon me, I went to Amsterdam, though bound in spirit;
and came thither about the middle of the second month, 1657.
I arrived there in a very seasonable and needful time; for Friends being but young,
and having had a pretty sore storm, were somewhat scattered and scattering,
being discouraged and frightened through the
indignation and wrath of the magistrates and priests,
which were kindled against them.
I made it my work to gather them together again,
and to establish them so much as was possible in the eternal truth.

Besides what they had met with from the magistrates, etc.,
there had been a bad instrument among them,
who had bred much discord and dissension among them;
but through the mercy and goodness of the Lord,
they came in due time to be restored again into faith and confidence,
peace and tranquillity, in which they kept their meetings.
But as for the professors, they were high and conceited,
and would scarcely believe that a greater light was sprung up in any part of the world,
than what was arisen among them;
neither could they well endure to receive instruction from
such as would not or need not be instructed by them.
There were also at that time many stumbling blocks laid in the way of the simple,
and many obstructions the truth met withal in that place;
and therefore were my burthens the more, and my sufferings the greater;
but the Lord was with me,
and the right hand of his righteousness upheld
me,--glory be to his holy name for ever and ever!

+++[+++The following valuable epistle from the Swarthmore Collection, is dated "`Amsterdam,
in Holland, 15th of third month,
1657:`" it bears an endorsement in the handwriting (as
the editor believes,) of George Fox,
thus:

William Caton to Friends, 1657.

To all my dearly beloved Friends that be elected of God,
sanctified through the Word of his grace to be vessels of honour,
to the praise and glory of his name everlasting: Mercy,
grace and peace be multiplied amongst you, from God, the Father of our Lord Jesus Christ,
the fountain of love and life, from whom all goodness doth come;
who hath distributed of the riches of his grace unto you,
and manifested his living power amongst you;
by which he hath quickened some of you who were dead in trespasses and sins,
and given you a sight of the entrance into the eternal inheritance,
which never fades away.
Yea, light is sprung up unto you who walked in darkness,
and upon you who dwelt in the land of the shadow of death, hath the light shined;
and your understandings hath the Lord opened, and given you to see that in yourselves,
which separated you from him;
and some of you are come to distinguish betwixt the precious and the vile,
betwixt that which entereth into God`'s kingdom, and that which is shut out.
So that which once you esteemed highly,
which did appear beautiful and glorious in your eyes,
comes now to be accounted dross and dung in comparison of that pearl,
which some have found, and many are digging for;
which is not purchased by all that seek it,
because they are not willing to part with their whole substance for it.
But I know that many of you have forsaken much;
and yet something remains which must be also offered,
even that which would save its life, and would not come to judgment,
must be brought to light and tendered,
if it be as dear unto you as your right eye or right hand.
Those who keep nothing back, but are willing to part with all for the truth`'s sake,
shall receive an hundred fold, and in the life to come life everlasting.
For I do assure you,
that none are ever made losers for parting with any thing for the Lord,
neither need they repent thereof; and that which you lose and have lost for the truth,
the time is at hand when you shall account it gain.
And though the world may account you fools, because of the loss of your reputation;
when your honour and dignity come to be laid in the dust,
it matters not for it is better to be reproached by the world,
and to suffer persecution of the world for righteousness`' sake,
than it is to revile them whom the Lord hath chosen out of the world.

Therefore eye his mercy to you, that are reproached and not reproachers,
persecuted and not persecutors; yea, I say, rejoice that you are accounted worthy,
not only to believe, but also to suffer for his name`'s sake.
Be ye comforted, in the midst of your deepest sufferings and tribulations,
with the consideration and hope of the joy and glory that shall be revealed unto you,
which your present sufferings, which are but for a moment,
are not worthy to be compared unto.
For the night is far spent in which the sorrows are;
and the day is at hand when sorrow and sighing shall fly away:
then shall you that mourn be comforted, and receive beauty for ashes,
the oil of joy for mourning, the garment of praise for the spirit of heaviness;
that ye may be called the trees of righteousness, the planting of the Lord;
although for the present you be in pain and sorrow,
groaning to be delivered from the bondage of corruption
into the glorious liberty of the children of God.
Be patient therefore and hope to the end, for he that shall come will come,
and will not tarry; whose arm is already stretched out,
in which he carries his babes and lambs, who are born again of the incorruptible seed,
nourished and fed with the sincere milk of the living Word,
by which they grow from strength to strength.
The Lord will not lay any more upon any of them than they are able to bear;
but he strengthens the weak, comforts the feeble, binds up the brokenhearted,
fills the hungry, clothes the naked, satisfies the weary and the thirsty soul;
whose everlasting treasury is always full,
and his banqueting house ever well stored with durable riches;
where the distressed are relieved, and every one`'s necessity supplied,
that hungers after righteousness.
For he is a Father to the fatherless,
and he increaseth the strength of such as have no might: so unto him you may come,
as unto a living fountain, from whence none are sent empty away,
who thirst and pant after the Lord.
Oh! blessed are all they that come to drink here of this Fountain of living waters;
their souls shall never thirst more: and you,
whose souls are thirsting and longing to participate of it, you shall be satisfied.
For I know that no visible created thing can satisfy that which longeth to
be refreshed with the living streams which issue out from this fountain,
which watereth and refresheth the whole city of God,--the
streams whereof make glad the hearts of the righteous,
whose souls come therewith to be everlastingly satisfied.

So come hither, all you that thirst, "`come ye to the waters, and he that hath no money,
come ye, buy and eat, yea,
come and buy wine and milk without money and without price;`" yea, eat, O friends,
eat abundantly and be satisfied; for a living fountain hath the Lord set open,
for Judah and Jerusalem;
and all that are bathed and washed in it come to enter into the holy city,
which hath no need of the sun nor of the moon to shine
in it;--for the glory of the Lord God doth enlighten it,
and the Lamb is the light thereof;--the gates of which are not shut at all by day,
for there is no night there;--neither can any thing enter into it that defileth,
neither whatsoever worketh abomination, or maketh a lie;
but they whose names are written in the Lamb`'s book of life.
And towards this your faces are turned,
and your feet are guided into the way that leads to it.

But woe to them that take up their rest by the way, and so come short;
they shall inherit sorrow and vexation, and trouble shall be their portion;
and with terror and great fear shall they inherit their possessions;
and poverty and distress shall be their garments, by reason of the drought,
scarcity and famine, that shall be In their inheritance.
But with the righteous and them that fear the Lord it
shall not be so;--for the Lord is their shepherd,
and they shall not want any good thing;--they shall eat
in plenty;--feed in pastures which are green and large,
and their souls shall delight themselves in fatness.
There shall no devourer or venomous beast come within their liberty to make them afraid;
neither shall there be scarcity nor desolation in their land;
for the dew from heaven shall fall upon it,
which shall cause it to bring forth more abundantly,
by which its increase shall be watered and refreshed;
for the Lord hath blessed their inheritance, and the curse shall no more come upon it,
neither shall the unclean enter into it,--but showers of mercy
shall descend upon it;--because the Lord hath blessed it,--yea,
and will bless it, and all their posterity, that inherit it for ever and ever.

So, my dear friends, know the seed of God in yourselves,
and dwell in the living power of God,
which will overturn and dispossess that which by
violence hath kept the seed of God in bondage;
that that which hath led captive may go into captivity,
and that which hath suffered violence under the violent oppressor,
may come to be set free.
Then will you see your Deliverer come forth of Sion, who purchased your redemption,
and will make you free from that which hath held you in thraldom and bondage:
then shall you return unto Sion with the ransomed of the Lord,
with everlasting joy upon your heads,--being made inheritors
amongst them that are sanctified and crowned with victory.

So, the everlasting powerful God, who is strong and mighty, bless, preserve,
and keep you;--that you may multiply, increase, and prosper,
and bring forth some an hundred, some sixty, some thirty fold,
to the praise and glory of our God--to whose custody and protection I commend you:
his grace and peace be with you for ever and ever, amen.

Your dear brother in the living truth,

William Caton.

When I had stayed there for the most part of seven weeks, I left Friends for a season,
having had very good service, not only at meetings, or the like,
but about getting books printed and published,
which were of good service in that country.

Afterwards I went with my dear brother William Ames
through some of the principal cities in Gilderland;
howbeit our movings were especially to a place called Zutphen,
a city out of which William Ames had been banished before:
and when we came there we went to the meeting place of the Mennonists,
otherwise Baptists; but when we would have gone in, they bolted the door,
and would not suffer us to enter in among them.
William being pretty well known in the city, the rude multitude gathered about us;
but to avoid the occasion of a tumult,
we withdrew out of the streets to the walls of the city,
and very many people followed us.
As we were moved and allowed of God, so we spoke in his power,
making known his eternal truth;
and a very good opportunity we had upon the walls of the city, from which we withdrew,
when we were free; howbeit,
the baser sort of people were very rude in throwing stones and clods at us;
but the Lord did so preserve us, that we received little harm thereby.
In the afternoon there came very many people to us out of the city to our lodging,
where we had also a very good opportunity to
declare the everlasting truth freely among them,
and to disperse many books in their own language, which we had brought along with us;
and several received pretty good satisfaction.
My dear companion had proposed to stay there some time,
but the magistrates being moved with envy, would not suffer the people to entertain him;
besides they took it as a great presumption in him,
that he should dare to return again thither, after he was banished from thence.
Moreover,
they threatened that if the Baptists came at us they should be served in like manner;
which threatenings, together with what they had done before,
kept the people much in fear and slavery,
so that they durst not appear to vindicate that of which they were convinced.

After we had good service in those parts, I returned again to Amsterdam,
where my service consisted much in keeping things in as good order as was possible;
and likewise in getting books printed and published, and in several other respects.
