== Chapter X.

1657--His service in several cities in Holland--The love of
God to him and Friends there--He returns again to England--
Attends a general meeting in Bedfordshire--Proceeds northward,
and reaches Swarthmore.

In this year (1657) I was at the Hague,
the place at which the head court is kept for the Seven Provinces:
there was but little entrance for the truth,
though I had some good service with some in that city.
I was also at the city of Dort when the plague was there,
where I found some two or three that were somewhat loving; howbeit,
there was little entertainment for the truth in the place,
and therefore was my suffering the greater.

I went also to the city of Utrecht to visit them that were convinced,
where I had now and then good service, and pretty fine meetings;
but in those days I spoke mostly by an interpreter.
When the magistrates and priests came to understand that the
truth seemed to get some entrance in that place,
their enmity began to increase against it; and they gave forth an order,
that those who entertained us, and had meetings at their houses,
should from thenceforth neither entertain us, nor have any more meetings in their houses,
on pain of being turned out of the city, or of being arbitrarily punished;
which threatenings terrified some, and caused some to draw back, but not all.

I was also at the city of Leyden, where their great university is;
there a Baptist woman received me into her house, whose husband was a Papist,
at whose house I was allowed to have a meeting, to which many sorts of people resorted.
The truth being a new thing and very strange, I met with no small opposition,
especially from the Papists and Baptists, both which sorts were stirred and offended;
and more so, because the man and woman of the house came to be convinced.
A meeting was in due time established in that city, where oftentimes,
as also in other places, I had good service for the Lord and his truth.
Most commonly, when my service was over in the country,
I returned to the city of Amsterdam which was a place of great concernment,
and where there was a more constant service than in other parts in that country;
in due time there was an addition to Friends, and the number of them increased;
their meetings were kept in very good order, and for the most part were pretty peaceable;
and the goodness and mercy of the Lord abounded much to the remnant that were gathered.

Sometimes the rude multitude was tumultuous and troublesome at our meetings:
once especially there were many rude people gathered together,
who doubtless had much wickedness in their hearts,
and some of the worst of them came into our meeting,
and sought to lay violent hands on me, and to have done much mischief to me and others;
but the Lord`'s power prevented them, and preserved me and Friends,
even to our admiration.
I was through Providence cast into a house in the presence of the rude multitude,
who if they had not been, as it were, smitten with blindness,
and restrained through the power of God,
might have executed their fury upon me and the rest; but he that was in us,
and by his power preserved us, was greater than he that was in them,
who in their madness would have devoured us at once: but blessed be the Lord our God,
who very often showed mercy unto us, and at sundry times,
with his heavenly presence and infinite loving kindness,
plenteously refreshed and comforted our souls;--
infinite praises be to his name for ever and ever!
When I had spent above a year in the service of the Lord in the Low Countries,
especially in Holland, in which time I had also written two or three books,
I was free in the Lord to return for England, which accordingly I did, through Zealand;
where I wrote the book called, "`The Moderate Inquirer,`" etc.
In due time I got well to London, through the mercy and goodness of the Lord,
where I found many of the brethren;
and several precious meetings we had in and about the city, to our great refreshment;
for about that time the truth did multiply, spread, and many were added to the church,
and came to receive the gospel.
For in those days the Lord endued his servants and
handmaids with very much power and wisdom from above,
and they went on in his name, preaching the Word of life,
both in season and out of season,
not only in the meetings which they were moved to appoint, and which Friends duly kept,
but also in steeple-houses and markets, in streets and highways, or elsewhere,
wheresoever and whensoever any was moved of the
Lord to publish and declare his living truth.

When I had been some little time in London,
I went into Surrey to some general meetings there near Reigate and Kingston;
where I was more than a little refreshed with Friends, and they with me,
in the power and presence of the Lord God,
which was often eminently manifested amongst us, to the comforting of our souls.

At the time called Whitsuntide, in the year 1658,
there was a general meeting appointed in Bedfordshire, at John Crook`'s,
to which I went with Friends from Kingston,
and unto which many hundreds of Friends resorted;
and some of the brethren came from most parts of the nation,
and great was our refreshment together in the Lord.^
footnote:[See George Fox`'s Journal for an account of this meeting, under date 1657-8.]
When it had continued about two days, there came some troopers,
who apprehended few or none, though some were in jeopardy: and afterwards we parted,
and went every one as he was moved, some eastward, and others westward, some northward,
and others southward: but I and a dear brother and former fellow servant,
whose name was Thomas Salthouse, went to the north, and visited Friends in our journey,
and came finally, through mercy, well to Swarthmore in Lancashire,
the place of our former residence; where we were received with joy and gladness,
and indeed great was our refreshment in the Lord, as it was wont to be in that place.
Divers precious and gallant meetings we had there and thereabouts,
which tended not only to our own refreshment, but to the refreshment of many more,
whose hearts were made truly glad, through the power and presence of the Lord God,
which did accompany us.

After I was abundantly refreshed at Swarthmore, and with Friends thereabouts,
I went into Westmoreland, according as it was upon me,
about the latter end of the fourth month, in the aforesaid year, 1658,
where I had some very good service among Friends at and about Kendal;
and afterwards I went out of those parts into the bishoprick,
where I had several large and precious meetings.
One was a very large, general meeting, upon a certain moor,
in a convenient place for Friends to come to from several parts of the country;
and the Lord`'s power and heavenly presence was very much with me that day,
even to the confirming of them that had believed in the everlasting truth,
and to the convincing of those there present who were giving their hearts to the truth.

After this meeting I went to Durham, where the same night I had a very good meeting;
for in those days it was common with us, while such an effectual door was open,
to get meetings in the evening, besides that which we had had in the day-time;
for we were freely given up to spend and be spent in the work of the Lord,
which in that day prospered exceedingly, to our joy and refreshment in the Lord.

When I had had very good service for the Lord in the bishoprick,
I went into some part of Northumberland, and visited Friends there,
and afterwards from thence to Carlisle, where I had very good service;
as also elsewhere in the county of Cumberland, where I had many precious meetings;
for in that county, there would come many hundreds to a meeting:
and our meetings were commonly very peaceable,
and the Lord was extraordinarily good to me,
and gave me his word plentifully to publish and declare
in the power and demonstration of his eternal Spirit,
to the confirming of many that had believed in the everlasting truth of God.

After I had visited Friends and their meetings in that county, and was clear thereof,
I returned again into Lancashire to Swarthmore,
where I was wont to find Friends in the same love, life and power in which I left them;
and it was very common with us, through the mercy of the Lord,
to be plentifully refreshed together in and through the same;
therefore had we many joyful and blessed days together,
the remembrance of which doth even unto this very day sweetly refresh me,
especially when I feel the same love and life fresh in myself, which then was,
and yet is, the author of our living refreshment.

When I was at Swarthmore, it was my manner, together with others of the brethren,
to go from thence to meetings in the country thereabouts, sometimes among Friends,
and sometimes to fresh places, where, it may be,
there had scarcely ever been a meeting of Friends:
for I made it my sole work to be found doing the work of God,
unto which he had called me, and for which he had in measure fitted and qualified me,
blessed be his name for evermore, who never suffered me to go without my reward.
