== Chapter XII.

[.chapter-synopsis]
* 1659+++.+++ He proceeds by sea to Sunderland, and passes westward to Swarthmore
* His services in Cumberland
* Travels to Edinburgh, Leith, and other parts, and returns to Swarthmore.

Being landed so far to the northward as Yarmouth,
I determined to go from thence by shipping; which accordingly I did,
with a Friend to Sunderland, where I found two of the ancient ministering brethren, viz:
Francis Howgill, and John Audland; with whom I was much refreshed,
as also with the rest of Friends.
And when first-day came, we went together to a general meeting in the country,
where there were abundance of Friends and others;
and the power and presence of the Lord was with us,
through which we were much refreshed together.

After that meeting I visited many Friends in the bishopric,
and in a short time after passed westwards towards Lancashire through Westmoreland,
visiting Friends in my journey, as my manner was.
I got well to Swarthmore, where I was received in the same ancient and entire love,
with which we were usually favoured together,
through the infinite mercy of the Most High,
which abounded much to us and among us in those days.

When I had stayed some weeks there, and thereabouts, I went into Cumberland,
to visit the flock of God there again, among whom I had many precious meetings;
for the power and presence of the Lord did accompany me,
and his Word of life ran freely and powerfully through me,
to the strengthening of the weak, the comforting of the feeble,
and to the satisfying of the thirsty soul.
When I had been through a great part of the county,
and had visited most of the Friends in it, I returned again into Lancashire;
where I could not stay long at that time,
because it was upon me to go into Scotland to visit Friends there.
I took my leave, even in an extraordinary manner,
of my dear and near relations in the eternal truth at Swarthmore,
where we spent several hours in waiting upon the Lord,
and in pouring forth our supplications before him,
and in being refreshed abundantly together,
after we seemed perfectly clear and ready to part one from another; which finally we did,
in much love and unity.

Being accompanied by two dear brethren, Leonard Fell and Robert Salthouse,
I went back again into Cumberland, and visited Friends in my journey thither,
where I heard much of the troubles that were in that nation,
and of the likelihood of their increasing;
yet nevertheless I could not be freed of the journey,
but must go on in the name and power of the Lord.
Presently after our coming into that nation,
the aforesaid brethren took their leave of me and I of them,
in the fulness of our Father`'s love, in much brokenness of heart;
committing one another to the protection and custody of the Almighty;
and afterwards I and another Friend travelled towards Edinburgh,
where through the mercy of God we arrived, after some hard travel.

The next day after our arrival, we went to a general meeting at Lythgoe, +++[+++Linlithgow+++]+++
about twelve miles from Edinburgh;
where we found Friends at their meeting by the highway side,
to which many people resorted, and good service we had at it.
Howbeit the people of the town were so incensed against us,
that we could scarcely get any entertainment among them for our money;
but the wife of the governor of the castle being at the meeting,
her heart was opened and filled with love towards us and the truth,
and she constrained us to turn in and take up our lodging in the castle;
which we were free in the Lord to do.
Afterwards we had some more good service in the town, which, when it was over,
I returned back again towards Edinburgh and Leith, where I had good service.

About that time it was pretty much upon me to speak with General Monk,
it being about the time of his advancing for England; but I was not permitted,
and was constrained to deliver my message or to make known my business to his secretary,
which he promised to communicate to his master,
whereupon I came to be pretty well discharged.

[.offset]
+++[+++The following letter is from the Swarthmore Collection:
Thomas Willan, it appears, was a Friend of Kendal.]

[.embedded-content-document.letter]
--

[.letter-heading]
William Caton To Thomas Willan

[.salutation]
My dear friend,

Such is my love to thee and to Friends,
that I cannot very well omit such an opportunity as this, when it is put into my hands,
but that I must let you know something of my welfare and of
the affairs of the gospel in these parts where I am;
knowing that it hath often tended to the refreshment of some,
even as I hope these lines in some respect will.
I for the present being somewhat far remote from you, even as in a forest, or wilderness,
where I should be in great jeopardy,
did not the arm of the Lord`'s power compass me about,
which is my buckler and sure shield of defence;
by which I was brought well through the country, to the city of Edinburgh,
the place towards which I was most pressed to hasten.
Staying one night in the city, I passed on twelve miles the day following;
when I met with several Friends to our refreshment in the Lord.
And having had two meetings together in that town of Lythgoe, +++[+++Linlithgow+++]+++
where the governor`'s wife of the castle is a Friend, we,
or some of us returned to this place; where sometimes the meetings are held,
and sometimes at the city of Edinburgh.
But for the present our meetings are but small, few strangers coming to them;
for many are surprised with fear who have some inclination in them towards the truth,
but dare not appear nobly to confess the same before men,
having little of the life of the same in themselves.
Since my coming into these parts I have had good service, sometimes among the soldiers,
sometimes among the Scots, often among Friends,
who are I hope benefited already by my being here,
this being not only a time of trial to them,
but to many men who are exceedingly jealous one of another.
This is a day wherein many are offended,
and because of the treacherousness and falsehood that one man beholds in another,
there is great hatred and emulation amongst men; insomuch that father is against son,
and son against father, one brother against another, one family against another,
and one nation rising against another.
What shall we say to these things?
Is it not the Lord`'s doing, thus to dash one potsherd against another,
that he alone may reign, whose right it is?
who is now arising in his mighty power, to break his enemies to pieces,
like a potter`'s vessel.

I have sometimes since my coming here endeavoured to speak with General Monk,
but could not have access to him; so the substance of that which was upon me,
as to him and the army, I wrote and gave to his secretary,
who promised to deliver it to him.
I also gave his secretary a copy of the same to communicate to the officers,
which he said he would do. He with several others who were present with me,
were pretty moderate and civil towards me.
Friends here with others were very desirous that it should be printed,
but it could not be got done here; and therefore,
it is sent to Newcastle in order to be printed; and if it be,
it is like that thou with Friends may see it.
I purpose shortly, God willing, to pass westward, and after I have visited Friends there,
I know not to the contrary but I may return for England.
For the present, the door which hath been opened seems to be shut in this nation;
where the spirits of men are much set on fire, and some are promoted, others abased,
and strange overturnings here are among the children of this world:
but the faithful and upright are little troubled at these things,
being confident that they will work together for good to those that fear the Lord.
For a further account I refer thee to the bearer hereof, George Collison.

Salute me very dearly to Friends that inquire of me,
and let them know that I am well at the writing hereof, praised be the Lord!
Many things I might write of, but not knowing in whose hands this may come,^
footnote:[This surmise seems to have been realised;
for by a few lines written by the said George Collison, at Carlisle,
on the back of the original letter, he states, that when he came near that city,
he was stopped by two troopers, who asked him if he had any letters;
on his informing them he had one, they took him before the governor.
It seems that great eagerness for information on the state of Scotland then prevailed,
that nation being reported by the writer to be at this period "`in a mighty uproar.`"]
shall therefore be sparing; and remain my dear friend and brother in the pure truth,

[.signed-section-signature]
William Caton

[.signed-section-context-close]
Leith, near Edinburgh, 14th of Ninth month, 1659.]

--

Afterwards it was upon me to visit Friends in the west of that nation, which I did,
to the confirming and establishing of them in the eternal truth;
and after I had had good service among them, I became pretty clear of that country,
and set my face again towards England.
I travelled mostly alone, after my fellow traveller had left me, and got well,
through the goodness of God, back to England again.

Upon my return from Scotland I visited Friends again in Cumberland,
and with some difficulty, it being in the winter season and very tempestuous weather,
I got back again into Lancashire, and so to Swarthmore,
which was always a place of refreshment to me.

[.offset]
+++[+++Editor`'s Note: About this time William Caton wrote a letter to George Fox,
dated from Swarthmore, 20th of Tenth month, 1659, from which the following is extracted.
After describing his service at Edinburgh, etc., he adds,
"`but at that time the hearts and minds of people were so taken up with the
bustlings and stirs that were among the children of this world,
that there was scarcely any room at all for the truth in them.
When I returned for England, I left Stephen Crisp in the west among Friends,
who is a pretty wise man that came from Colchester;
and he was determined to stay some time in that nation.`"--Swarthmore Collection.+++]+++
