== Chapter XIII.

[.chapter-synopsis]
* 1659-60+++.+++ His service in the South of Lancashire
* Attends a general meeting at Balby in Yorkshire
* Travels to London, also into Sussex, Kent, and so into Norfolk
* Returns to London and proceeds to Dover.

When I had continued at Swarthmore some time,
it was upon me to go into the south of Lancashire, to visit Friends and their meetings;
which I did,
and had several good and serviceable meetings in divers of the great towns in Lancashire,
as at Garstang, Preston, Wigan, Liverpool, and Warrington, etc.

Being at a meeting in Warrington, the 7th of the twelfth month, 1659,
there came several rude soldiers of the baser sort, who did much abuse Friends;
and after they had done much violence to us, they broke up our meeting,
and forced us out of the town: but we gathered together again,
near to the town upon the roadside, and had a sweet and precious meeting.
It was not long before the soldiers came thither also,
and as I was speaking they took me violently from among the rest, and beat me,
some with their muskets, and others with their spears, in the sight of Friends,
to the breaking of the hearts of many.
When they had satisfied their wills with abusing me,
they suffered me to return into the meeting again,
which afterwards we kept a certain time to our great refreshment in the Lord,
whose power and presence did exceedingly appear amongst us;
for as our suffering at that time was greater than ordinary,
even so was our refreshment in the Lord.
I visited Friends in some parts of Cheshire and elsewhere;
and when I had had good service in those parts, I returned again to Swarthmore,
where I always found refreshment in the fulness of the Father`'s love,
which abounded much among us in that blessed family.

I had not been long there, and with my own dear mother,
who about that time laid down the body, when I was with her,
but it was upon me to go southwards,
first towards a general meeting of the brethren from several parts of the nation,
which was at Balby in Yorkshire, and afterwards towards London;
and it was so ordered that Thomas Salthouse, my dear companion and fellow servant,
together with Bridget and Isabel Fell, did accompany me.
When the time of our departure from Swarthmore was come,
our hearts were sad and broken within us, as they used to be at such seasons;
and when with prayers and supplications unto the
Lord we had earnestly interceded one for another,
and had committed one another to his custody and protection,
as our manner was at such times,
we took leave one of another in the fulness and virtue of love and unity;
and then set forward on our journey, in the name and power of the Lord.

When we came into Yorkshire, we had some meetings;
and when we got to Balby we found many of the ancient brethren there,
and Friends that were come from several parts of the nation;
so that the meeting consisted of many hundreds.
When it was about the height, there came a part of a troop of horse to break it up,
and dismiss Friends, but they were moderate,
and Friends continued their meeting until they had freedom in the Lord to break it up.
The next day we had a very large and precious meeting, not far from that place;
and when we were abundantly refreshed together in the Lord,
through the abounding of his mercy and goodness to us,
we took leave one of another in much love and unity,
and every one went in peace towards his respective
place where the Lord had a service for him.^
footnote:[See an account of these meetings in George Fox`'s [.book-title]#Journal#,
under date of 1660.]
The aforesaid Thomas Salthouse, my dear brother, and I,
travelled southwards towards London, and visited Friends in our journey.
As we were travelling in Nottinghamshire,
some troops met us upon the road and apprehended us,
and carried us before some of their commanders,
who sent us to the commissioners at Nottingham,
where we were further examined by some of them, and being found innocent were discharged,
and suffered to pass on our journey in peace.

Coming into Northamptonshire we visited Friends at Wellingborough and thereabouts,
and being sweetly refreshed among them, we took our leave of them,
and travelled along until, through the mercy of the Lord, we came well to London;
where we had several precious meetings,
and were more than a little comforted with the flock of God there,
as oftentimes my soul had been before in that city.
I stayed about two weeks, and afterwards parted with my dear brother Thomas Salthouse.

[.emphasized]
+++[+++The following letter,
descriptive of the state of things in London at this period may be here inserted;
it is taken from the Swarthmore Collection.+++]+++

[.embedded-content-document.letter]
--

[.salutation]
William Caton and Thomas Salthouse To Thomas Willan.

[.signed-section-context-open]
London, 7th of Third month, 1660.

[.salutation]
Dear friend,

Our dear and unfeigned love reacheth to thee, and to the brethren with thee,
whom we dearly salute in the living Truth.
We rejoice in the Lord,
who lifteth up our heads above the wickedness of wicked and ungodly men,
which indeed is grown to an exceeding great height in this city;
which doth exceedingly abound in pride, fulness, excess,
and in all manner of superfluity of naughtiness,
to the grieving of the spirits of just men, and to the making of their hearts sad,
who fear the Lord and work righteousness.
Yet, nevertheless, this we would have the brethren to know,
that as yet we see scarcely any stop at all put
to the work of the Lord in the city or country.
For several precious meetings we had, as we came through the country,
as a letter that is coming by the carrier, makes mention of, more at large,
than at this time we shall do.

As for the meetings, in general, in and nigh unto the city, they were,
the last first-day, as full, large and peaceable,
almost as Friends have at any time known them;
and abundance of sober people resorted to them and were generally quiet--the
guard of soldiers which for a season was kept at the Bull and Mouth,
is now removed from thence; and several quiet,
large and precious meetings we have had there of late, since the guard was removed,
which is not only removed from thence, but also from several parts of the city.
It is reported that the citizens would have all the soldiers
of the old army removed out of the city forty miles,
or rather disbanded;
and they would undertake to guard and to protect the king and parliament.
The old soldiers are in great contempt, and with most they are holden in derision,
and that dreadfulness which once attended them is now departed from them,
and others that dreaded them are now become a dread unto them.
Indeed, now are anguish and distress come and coming upon many,
whose hearts have been nourished, and exalted, and puffed up without the fear God;
who have not regarded the cries of the oppressed, nor stood in God`'s counsel;
but have boasted themselves against +++[+++those+++]+++
that hewed with them once.
Therefore, is it just with the Lord to give them for a prey to their enemies,
who were a prey to them, while they stood in God`'s counsel;
from which many of them have departed, and therefore are they fallen, snared and taken.

Friends in the city are almost generally well, as far as we know.
John Stubbs is gone into Kent, Richard Hubberthorne is yet in the city.
The chiefest discourse among the people here is,
about the king and the parliament`'s proceedings;
who are speedily preparing the way for his coming, which is suddenly expected:
but blessed be the Lord forever, in whose power we can testify, that our King is come,
who reigns in power and great glory; and therefore we need not look for another.

[.signed-section-signature]
William Caton

[.signed-section-signature]
Thomas Salthhouse.

London, 8th of Third month.--
This very day the king hath been proclaimed in an extraordinary manner;
the concourse of people that have been in the streets has been innumerable;
the shouting for joy hath been so exceedingly great among the people at times,
that the sound of many trumpets could scarcely be heard,
nay the bells themselves could not sometimes be heard,
but the noise hath been exceedingly confused, like the noise of many waters.
Time would fail me to relate the fantastical ceremonies that have been used,
and the extraordinary pomp, the mayor and aldermen with the gentry have appeared in.

Oh! the vanity and superfluity of wickedness which hath appeared in the city,
my pen could not declare it in several hours`' time to the utmost.
But at present I have not much time, being about to go to a meeting,
not knowing certainly whether this day they will suffer us to keep any of our meetings;
for they would not suffer that at Westminster to be kept this day.
This wickedness, which is now at an extraordinary height,
will have an end in the Lord`'s time.
Let this be sent to Swarthmore, after Friends have seen it at Kendal;
my entire love is unto all the faithful there and elsewhere. Farewell.

[.signed-section-signature]
William Caton

My dear love in that which is our life, is unto you all,
and if George Fox be there I would gladly hear from him, as he is free.
As for the sufferings of Friends,
which George Fox said should be given to this parliament,
it is not yet a convenient time to present them,
because they do not act any thing till Charles come,
but what is in order to the bringing of him in,
and so they were but lost to be given to them at present.

[.signed-section-signature]
Richard Hubberthorne

[.signed-section-context-close]
London, 8th of Third month, 1660.

--

[.offset]
Returning to Journal:

I went down into Surrey and Sussex, where I had very good service for the Lord,
and many precious meetings, which were of great service at that time.
At Hurst in Sussex, upon the 27th of the third month 1660, I had a very large meeting,
to which many Friends from several parts of the county resorted,
together with many others that were not Friends;
and an exceedingly precious and serviceable meeting it was,
but weighty and heavy upon me, before I went into it.
But this I have often observed and found by experience,
that by how much the more I felt the weight of the service of the meeting,
before I went into it, by so much the more was my service in it,
and my reward accordingly; blessed and magnified be the name of the Lord forever!

At that time it was somewhat difficult travelling,
by reason of the many watches that were set with a strict order, as I was informed,
to apprehend all suspicious Quakers, Baptists, and Papists; howbeit,
the Lord was pleased to preserve me out of their hands.
At the time called Whitsuntide, we had a very precious and large meeting near Horsham,
of Friends out of four counties, according to appointment; which we enjoyed,
through mercy, pretty peaceably, to our great refreshment in the Lord;
who in those days did very eminently manifest his
heavenly power and presence in our assemblies,
to our great consolation in Him.

After the aforesaid general meeting was over, and I was clear of that county,
I went into Kent, where I visited the brethren, and had many large and precious meetings,
which tended much to the confirming and establishing Friends in the truth,
and to the convincing of those that heard the same eternal truth declared.

When I was clear of those parts, I returned again to London, where I stayed some time,
and had good service.
Afterwards I went into Essex, Suffolk, and Norfolk,
and visited Friends and their meetings in many places of the aforesaid counties,
where I had as excellent good service as my heart could desire;
for the Lord`'s refreshing presence went along with me,
and the word of his power supported me,
and carried me through the great and weighty service,
in which I was so much exercised in that blessed day,
wherein the truth did flourish and prevail mightily in very many parts of the nation;
which was no small cause of joy to us, who were witnesses of it.

I returned again to London, where I always found service enough,
and for the most part a door open in that city.--When I had been some time in it,
and had had good service there and thereabouts, it was upon me to go over to Holland;
and I returned into Kent after I had in much brokenness of heart,
and in perfect love and unity taken my leave of Friends and brethren at London.
In passing through the country I visited Friends and their meetings, as my manner was;
and I stayed several days at Staplehurst, with Thomas Housegoe,
who then lay upon his deathbed,
who had been a serviceable instrument in his day in those parts;
and after he was laid in the ground, we had a very precious meeting,
there being many Friends at his burial.

+++[+++At Dover, he writes to his friend George Fox,
under date of the 16th of Ninth month, 1660;
from which letter the following are extracts.+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
William Caton To George Fox

Since I came from London, I have had good service in this county, at Sutton, Cranbrook,
Tenterden, but especially at Staplehurst, and in Thomas Housegoe`'s family;
for it was so ordered that I came to his house the same day that he began to be very ill,
and that very night I began to despair of his life; a day or two before he died,
he gave a very good testimony to the truth,
to the power and to the glory that is now revealed, etc.
It was upon me to stay till his funeral was over, which was last third-day;
and abundance of Friends were at it, yea, several out of Sussex,
so that it was a very honourable burial.
After his body was laid in the ground.
Friends drew nigh into the meeting place, with several of the world,
where we had a precious meeting;
for the power and presence of the Lord were abundantly manifested amongst us,
to the consolation of Friends in general.
That night it was upon me to return to his house again, where I had very good service,
and in the morning I left them in a pretty good hopeful posture;
but assuredly he will be very much missed in those parts,
and I believe there will be now more necessity of Friends
visiting them pretty often than there was before:
I desire that thou wouldest be mindful of them.

I have also been at William Beeme`'s, and at Hythe, and at Folkstone,
where I find Friends very well,
but some in deep sufferings for that unhallowed ordination of tithe;
some are in prison at Canterbury, and some in Dover Castle, for refusing to pay it.
Yesterday I came to this town,
and had a very good meeting yesternight among Friends here,
who are as well as ever I knew them.
Since I came to this town, I have been to see for shipping,
and there are some vessels ready;
it is thought they may set sail either this night or tomorrow at night,
if the wind continue fair.
I purpose, if the Lord will that I can get passage, to pass by them to Zealand,
and go from thence to Holland;
but the officers here that look after passengers are very untoward bad men;
so how the Lord will order it, I know not at present.
Dearly beloved of my soul, let thy prayers be for me, that I may be kept in the power,
life, and wisdom of our God, to his praise,
and to the comfort and consolation of the brethren, with whom I can rest in the Lord,
even in the heat of the day; glory be to the Lord forever.

[.signed-section-signature]
William Caton.

--

+++[+++From Swarthmore Collection.+++]+++
