== Chapter XVII.

[.chapter-synopsis]
* 1663--He visits Friends in Cumberland
* Proceeds into Durham
* At Scarborough takes shipping for Holland, but reaches Yarmouth Roads
* Is driven back by storm again to Yarmouth, where he is committed to prison from Eighth month, 1663, to Second month, 1664.

After being at Swarthmore I went to Lancaster, Kendal, and other places,
and visited Friends in those parts to our mutual comfort.
It was upon me to go into Cumberland, which I did, so far as to the city of Carlisle,
where I visited Friends in prison, and there, even in the prison,
I had a very precious meeting;
and afterwards I visited Friends in several parts of that county,
to our great refreshment in the Lord.

When I was clear of that county, I returned again to Swarthmore,
and there I found dear George Fox.
Dear Margaret Fell was also returned home,
which tended to the augmenting of my rejoicing which was great at that time with them,
the family and Friends.
I had not been long there when it was upon me to return again for Holland:
but in the interim I went over to Lancaster to a general
meeting which was held there in the assize week;
and some occasion I had with some of the justices, as in reference to a certificate,
which three of them granted me under their hands and seals,
there being then reports of a plot,
and for preventing my being stopped upon suspicion without cause.
I therefore had their certificate, and returned again to Swarthmore;
where I stayed but a little, when I took my leave of them in the fulness of endeared love,
and with much brokenness of heart, and so I left them,
being accompanied by several of the brethren into Westmoreland;
and after we were much comforted together, we took leave one of another,
and parted in the same love and unity in which
we had been so plenteously refreshed together.

I travelled into the bishopric, and visited Friends there, and went to Durham,
and visited those that were in prison; and from thence went to Sunderland,
and had a general meeting betwixt Sunderland and the Shields.
Upon inquiry after shipping for Holland,
I heard of several that were preparing to go over, but the wind being contrary,
and being desirous to visit more Friends, I travelled along the country,
not far from the sea-side, visiting Friends as I went, at Shotton, Stockton, Whitby,
and elsewhere, and had some very good meetings.
When I came to Scarborough, I heard of vessels there also,
that were intended for Holland.

After I had had a very good opportunity with Friends there, to their and my refreshment,
the wind being fair, and the ships ready to sail, I took my leave of Friends,
and went aboard one; but soon after, we met with contrary winds: howbeit,
we got up as far as Yarmouth Roads, and there waiting awhile,
the weather being pretty good, we set sail again, intending to run over,
if the Lord permitted.
When we were got about ten leagues, I was much persuaded we should have a storm,
and told the master of it, and would have had him return again for England;
it being then indifferent weather, he did not much mind my words,
but endeavoured to press forwards, though the wind was contrary.
But that night following, according to my persuasion and expectation,
we had a very sore tempestuous storm, and our ship proved very leaky;
so that what with pumping and other extraordinary work,
the men were exceedingly wearied and toiled.
To outward appearance we were in much danger,
for about the very height of the storm in the night
season we lost the use of the helm for a time,
so that the poor men were in great distress.
In the meanwhile my soul interceded with the Most High, who heard my requests,
and granted my desires; though for my own part,
I was freely given up to the blessed will of the Lord,
if it had been to have made my grave in those great deeps.
But the Lord was determined to show mercy unto us, which evidently appeared,
in his bringing us, through such apparent danger among the sands,
even finally back to the English coast again:
for which extraordinary mercy my soul hath cause forever to bless,
praise and magnify his glorious name.

Afterwards we got well, through mercy, into Yarmouth Roads again,
and the wind remaining contrary, we put into the haven, and I went up to the town,
where I waited some days for the wind.
In the mean time the first-day of the week came,
and it was upon me to go to the meeting of Friends, which accordingly I did;
and about the end of it, there came several officers and soldiers,
and apprehended seven Friends, besides myself, who were strangers in the town,
five of whom belonged to one vessel; and they carried us to the main-guard,
where they kept us that night;
and very good service we had with the officers and among the soldiers;
and the next morning we were brought before the bailiffs of the town,
who tendered us the oath of allegiance; and because we refused to take it,
or any oath whatsoever, we were committed to prison upon the 4th day of the eighth month,
1663, and continued in prison until the 22nd of the second month, 1664;
and then I with the rest of my fellow prisoners was discharged.

[.offset]
The following interesting Epistles,
nearly all of which are from the [.book-title]#Swarthmore Collection#,
will serve to carry on the narrative beyond the period of the termination of the Journal.

[.embedded-content-document.epistle]
--

[.letter-heading]
William Caton To Friends.

[.signed-section-context-open]
Yarmouth Common Jail, 9th of eighth month, 1663.

[.salutation]
Dear and affectionately beloved Friends,

In the everlasting fellowship of the gospel of peace,
into which we are brought through the arm of God`'s eternal power,
do I dearly and tenderly salute you; who are dear and near unto me in the truth of God,
which he hath made known unto us, to the comfort of our souls;
whereby he hath engaged us above all the families of the earth
to love and to serve him with reverence and godly fear.
And though they that are without,
do judge we are losers through our knowledge of the Truth,
yet we find that we are become gainers through it;
for if we lose the love and peace and liberty,
which the world in times past hath afforded us,
we have gained the peace of God and liberty in his eternal Spirit;
if we lose that honour and treasure which are of the world,
and which we have had in the world, we are honoured of our God with bearing his name,
and we are become sharers, with the rest of his sanctified ones, of heavenly treasure,
which the world cannot give us, neither can it take away from us.
So that whosoever deem or imagine we are losers through our coming to be of this way,
or by our coming to the knowledge of this eternal Truth, I say, nay;
for the things that we have lost by reason of it, being but as dross and dung,
are not worthy to be compared to what we have gained through it.
Shall not we therefore love the Truth?
and shall not we be willing to suffer the loss
of all this world can afford us for its sake?
For can we have a better cause to suffer for than the Truth?
Can we suffer upon a more honourable account, than upon the Truth`'s account,
upon the account for which all the righteous men, who have suffered in all ages,
have suffered?
And who are we that we should be called to this high and
honourable calling?--or that we should be accounted worthy to
become witnesses of this ancient Truth in this generation,
to bear our testimony unto it with the rest of the faithful witnesses,
servants and handmaids of the Most High!
The consideration of these things I confess might even
be enough to break and overcome our hearts,
and to engage us, as it were, afresh unto our God, who hath chosen us and loved us,
before we loved him or made choice of him to be our Lord and God;
whom we have found to be so exceedingly gracious and merciful to US-ward.
Let our souls and spirits therefore praise and magnify him forever and ever!

And now, Friends, you may hereby understand,
how that after I had had a very precious opportunity with many of you in the north,
to my great refreshment in the Lord, I was clear in myself to return again for Holland;
and in order thereunto, I passed towards the sea-coasts; and when I came there,
I heard of ships that were nearly ready to go for Holland,
both at Newcastle and Sunderland.
But the wind being out of the way or contrary,
and I being desirous to improve my time to the utmost,
and withal being very desirous to see as many Friends as I could before I took shipping,
I travelled along the coasts towards Whitby and Scarborough,
and had some very good and precious meetings among Friends by the sea-side.
And finding a ship ready at Scarborough, and the wind being good, I went aboard her:
but the wind came contrary again:
howbeit we kept out at sea and that for the space of nine days,
whereas if the wind had been good we might have sailed it in two days.
But finally a tempestuous storm came upon us, of which I had had some sight before,
and told the master of it, and would have had him return again for England;
and indeed it was so violent that as to outward
appearance we were in very imminent danger;
and the more so because our ship had a sore leak, or rather more than one,
and sometimes the pump was so out of order that it would do no service,
and besides they had lost the use of their helm, even in the very height of the storm.

In the meantime the ship was in no small danger of being foundered or overset;
and as for the poor men they were as if they had been plunged into the sea,
and by reason of their continual pumping,
besides the extraordinary toil they had with the sails,
they were so exceedingly wearied out,
that their courage and strength were very much departed from them.
In which time I did much intercede with the Lord,
and did with much fervency of spirit wrestle with him,
that if it was his will their lives might be spared,
and we preserved out of that extreme danger;
though as for my own part I found myself freely given up to
bequeath my soul into his bosom of everlasting love,
and my body to be buried in that great deep:
indeed I confess I could sometimes expect little else.
At that time I could have bid you all farewell, and all that in this world I do enjoy,
and could have gone to my everlasting home in peace with my God;
who even then beheld my meditations and intercessions; and because he loved me,
was he prevailed withal, even for his mercy`'s sake, who was determined, as appeared,
to show mercy unto us.

For when we were near the sands,
where dear Hugh Tickhil`'s wife and another Friend were cast away, as I am informed,
in their passing for Holland, the Lord was pleased to cast us betwixt two sands,
which if our ship had come to strike upon either,
she must in an instant have become a wreck.
But blessed be the name of the Lord who preserved us out of that imminent danger,
whereby he hath exceedingly engaged me unto him,
and his unspeakable mercy I hope shall be held
in a perpetual remembrance by me his servant;
who at this time do make mention of this deliverance unto you,
to the end that you may know how good the Lord hath been to me,
and that you with me may return thanks unto him;
not only for his mercies in general to us-ward, but for this to me in particular;
the consideration and sense of which have more than a little broken my heart,
which hath been filled with praises unto the Most High.

Moreover, Friends, I would have you understand,
that the Lord having delivered me out of the storm before mentioned by sea,
he hath suffered me to come into another by land among unreasonable men,
who are like unto the waves of the sea.
But he that limits the one, limits the other;
and I am confident that he that hath preserved me in the one,
will in due time deliver me out of the other.

By contrary winds, after we had been nine days at sea or thereabouts,
we put in here at Yarmouth; and on a first-day I went to the meeting of Friends,
which was a precious peaceable meeting: at the end of it,
when we were standing up to depart, officers and many soldiers came there,
and carried eight of us away prisoners to the main-guard,
where they kept us that night among the soldiers;
and the next day we were carried before the magistrates of the town,
who presently tendered the oath unto us.
I told them, I had never sworn but one oath in my life, that I knew of,
and that was when I was a boy; and I had known the terrors of the Lord against the thing,
and therefore I durst not swear again.
But without any respect to my or our tender consciences,
they committed us to the common jail;
and so much confidence they had that we would be true to our principle,
that they had made out our mittimus beforehand, yea, before they examined us;
wherein the only thing charged against us was for refusing to swear.
We were all strangers to the town, come occasionally and accidentally to it;
for five of the Friends belonged to one vessel in the town,
who were come hither to load with herrings for the Straits, one of them was the merchant,
another the master, another his mate, and the other two seamen;
the others are Friends out of the country:
and there are warrants out for apprehending Friends in the town also.

And very high they are, (as the sea was for a season;) and they keep Friends from us,
and would force us to have what we have occasion for of the jailer,
which we cannot consent to, though we suffer five times more than we do at present.
But notwithstanding their fury and rage against us,
it is well with us,--blessed be the Lord; and we are resolved, in his name and power,
to bear our testimony for the Lord in this place,
as many of our brethren have done elsewhere.
For my own part I am perfectly satisfied in the will of the Lord,
not so much admiring at my present bonds,
as I have admired sundry times that I have been so long kept out of bonds;
unto which I have long been freely given up in the will of God,
where my soul is in peace with the Lord.
Unto him who hath gathered you by the arm of his power,
and who is able to preserve you unto the end, whose name is called the Lord of hosts,
do I commit you all; with whom I remain,
in the unity and fellowship of the eternal Spirit of life, your dear friend and brother,

[.signed-section-signature]
William Caton.

--

[.offset]
An extract from an Epistle of William Caton to Friends,
dated a few days after the preceding one;
it is from a collection of copied letters from Colchester.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friends,

How near at hand we found Him unto us, even as a rock of defence to fly unto,
in our greatest straits, difficulties and temptations!
And what free access have we had unto Him through his eternal Spirit in ourselves,
when by jails, houses of correction, force of arms, or the like,
we have been hindered from having access one unto another,
or from meeting together in the outward!
How did we rejoice in the Lord, when he covered our heads as in the day of battle,
even until the fury of the wicked came to be abated!

And forasmuch as in these perilous times,
we cannot well serve our God in that way in which He requires us to walk,
without being in jeopardy of bonds and imprisonments,
or of having other sufferings imposed upon us,
by reason of our meeting together to wait upon the Lord;
it doth so much the more concern us to feel the drawing
of our God by his eternal Spirit to our meetings;
that when we are met,
we may so much the more enjoy His presence to the refreshment of our souls.
And then if we suffer for waiting upon him,
he will not leave us comfortless in that suffering; neither will it be grievous to us,
while we keep in that through which we enjoyed him in our meetings,
for in that we may enjoy him in our sufferings:
and then it will be better to be one day in prison with the Lord,
than a thousand elsewhere without the enjoyment of his presence, in which we have found,
as you know, much joy and peace, much comfort and consolation.

I suppose many of you have heard of my bonds,--how that after God, of his mercy,
had delivered me out of a mighty violent storm at sea, I was cast in here;
where they in authority have shown themselves to be worse to me and the Friends with me,
than the barbarous people of Melita were to Paul and them that were with him;
who showed them no small kindness, for they received and lodged them courteously.
But these that are called Christians, showed themselves far from courteous,
in that they broke up our meeting with many soldiers,
and afterwards committed us to prison; and instead of showing us much kindness,
they have been so cruel to us,
as that sometimes it was difficult for us to get water and bread.
Howbeit, the Lord is with us, and their cruelty hath been little to us;
for we know that our God will, in his own due time, deliver us out of their hands,
when our testimony is sufficiently borne.
Of this I am very sensible,
that with the baptism of suffering under this spirit of persecution in the nation,
many are to be baptized into the fellowship of the gospel with the saints in light.
And blessed and thrice happy are they, and will they be,
that continue faithful unto the end,--for they shall be saved.
Farewell in the Lord, in whom I remain your dear friend and brother,

[.signed-section-signature]
William Caton.

[.signed-section-context-close]
Yarmouth Common Jail, 14th of Eighth month, 1663.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Addressed to T. S. and J. P.

[.salutation]
Dear brethren, T. S. and J. P.,

Yours dated the 12th of last month I have this afternoon received,
to my refreshment in the seed immortal; in which I feel your love extending to me,
and perceive your sympathizing with me in these my bonds;
in which the Lord hath been pleased to try me a little,
together with the rest of my fellow prisoners,
even as he hath tried many who are now at liberty as I was, when they have been as I am:
but blessed be the Lord it hath been a good time for me;
and as I think I told you before, much I have enjoyed of the Lord since my confinement,
and his love is perfectly continued unto me,
in which my soul doth solace itself night and day.
And much I could say unto you,
if I were with you and the rest of our dear and near relations in that blessed family,
who know my voice and integrity, my love and simplicity;
which is also pretty much known to many more, whom I love in the Lord.
In these parts I find the love of Friends to be much to me;
but they are but seldom permitted to come in to us,
for the bailiffs do absolutely gainsay it, for fear, as they pretend,
lest they should bring in ammunition to us, books or letters, etc.--Howbeit,
in eight weeks`' time, through the providence of the Lord and our patient long suffering,
our persecutors are brought so far as that they now do in part
condescend to suffer provision to be handed in to us at the door.
The last seventh-day the jailer caused the door
to be opened for provision to be brought in,
which was more than ever he had done before;
yet on the last second-day they were so high again,
that when Friends would have brought in a spinning wheel, they would not suffer them;
and they going about to pull it up at the window, the turnkey cut the cords.
But enough as to these things, for the Lord is with us; through whose word,
power and Spirit we doubt not,
but we shall in his time become victorious through suffering;
as our Captain and thousands of his followers have been.

I was truly glad to hear of your liberty, and of Friends`' welfare,
and of the peaceableness and preciousness of your meetings in those parts;
and especially of the well-being of that honourable family,
and also of dear George Fox`'s liberty yet in it, which I know is no small mercy to it.
I desire to be dearly remembered to him, also to dear Margaret Fell,
and to all her dear children; unto whom my affectionate love is, as you right well know,
as unto the rest of the family.
I was glad to hear that my general epistle was come well to hand,
and that it had such influence upon the hearts of our
beloved Friends in the meeting to their refreshment.
It is much with Friends in these parts, as you relate it is in the north,
viz. the meetings are mostly pretty quiet, blessed be the Lord;
but many of them are cited, and some excommunicated, and others have their goods spoiled,
for not repairing to their devised devotion.
I am yet very well, blessed be the Lord; so are we all.

My dearest love is with you, my dear brethren.

[.signed-section-closing]
Farewell,

[.signed-section-signature]
William Caton.

[.signed-section-context-close]
Yarmouth, 1st of Tenth month, 1663

--

[.embedded-content-document.letter]
--

[.letter-heading]
Addressed to James Moore, woollen-draper, Kendal.

[.salutation]
Dear James Moore,

With the salutation of dear and unfeigned love, do I dearly salute thee,
and all our dear Friends and brethren with thee;
and being sensible of your desires to hear of me,
to the end you might know how it was with us at the sessions,
these are therefore to inform thee, together with the rest of Friends,
that we were not once called at the sessions.
When I saw they had adjourned their court, I went and spoke with the clerk thereof,
to know the reason why we were not called; he said,
because the court was minded to favour us: for if we had been called then,
there must have been a bill of indictment preferred against us,
and the oath tendered again to us,
and then we should have been more liable to have been premunired, etc.
He said further, if we would but give sureties for our good behaviour,
we might go about our business and the like.

Afterwards I wrote to the judge and to the bailiffs;
and the chief collector of this town took it from me, and gave it to one of the justices,
who willingly carried it to the judge, and did plead our cause pretty much;
the judge was a moderate wise man, and willing that we should have our liberty;
and though he was in much haste to be gone out of the town,
yet he prescribed to them a way how they might clear us, viz:
by taking any one man from the quay, though but a porter,
and he might serve to be bound for a hundred of us;
and when he came again he would take it off the file, so that we should not be called,
neither needed even to appear any more.
Further, he knowing our tenderness of conscience,
ordered that the clerk should take nothing of us;
neither would he have had us further troubled or longer detained.
And this, one of the justices, that carried our paper and is our great friend,
sought further to have accomplished, to the end that we might have our liberty;
but when the judge was gone, some of our grand adversaries consulted together,
and resolved to perpetuate our bonds,
except we should yield and give our consent to the recognizance:
though they did not desire that we should come to appear at the sessions,
yet they would have us to submit to satisfy their wills more or less;
and because we cannot satisfy them, therefore are our bonds continued.
Howbeit, the aforesaid friendly justice is very much dissatisfied, and told the rest,
in the hearing of one of our friends, that he could not be quiet,
and would not be quiet till he had us out; and in order thereunto,
he labours yet very much to procure our liberty, but what the end thereof will be,
time will manifest: in the mean time we hope to rest satisfied in the will of our God.

At Norwich there are several of our friends in prison, some committed from the assize,
and some from the session,
being fined for keeping on their hats in their courts of judicature.
Since the assize,
meetings have been broken up at some places in these parts;--
for the judge was very high and severe against the fanatics,
so called, in his charge and proceedings.
But Friends are sweetly kept, blessed be the Lord;
and the truth is of good report and of good esteem among the upright in heart,
notwithstanding the tribulation which comes upon them by reason of it.
This very day we have had more visitors,
than we have had in all the time that we have been prisoners here before;
and much pity seems to be in the hearts of people towards us;
and good service we had with them:
but blindness and ignorance hath happened to the most of them.
The chief occasion of their coming to the jail was to see some condemned persons;
and being here they came to see us also, and finding every man close at his work,
the sight was so much the more strange to them.

I have little else to communicate,
besides the redoubling of my salutation of true love unto thee and to all the brethren.
I am, dear James, thy real friend and brother,

[.signed-section-signature]
William Caton.

[.signed-section-context-close]
Yarmouth, 18th of Second month, 1664

P+++.+++ S.--The vessel out of which my fellow prisoners were taken,
when they were put in prison here, was taken by the Turks, and carried into Algiers;
so that though our persecutors intended it for evil towards them,
yet the Lord may have suffered it to come to pass for their good:
and one of them having heretofore been a slave in Turkey,
knows what a miserable servitude it is.
But the Lord knows right well, how to order things for the best, to them that fear him.

--

[.offset]
At the period of the following Epistle, we find William Caton in Holland;
it is dated Rotterdam, 16th of Tenth month, 1664.

[.embedded-content-document.letter]
--

[.salutation]
Dear and entirely beloved friends,

The love and affection that abounds in my heart
towards you in the Lord I cannot easily express,
nor the fervency of my desire to the Lord for you;
yet however herein can I satisfy myself,
in that we are come to read and feel one another in that which
is immortal--which tongue (to the full) cannot express,
nor pen (to the utmost) demonstrate; and even through this, which is immortal,
doth my love extend unto you; and with the sense of your love,
and the mercy of God to you and me, is my heart broken, my spirit melted within me,
and mine eyes filled with tears.
And what is that which thus breaks and overcomes me?
surely it is nothing but the sense of the same love and life,
which we have felt one in another, when we were together,
to the comforting and refreshing of our souls.
And though I am far separated from you as to the outward,
yet I am not destitute of that which your souls delight in, nor deprived,
through my external separation, of your joy and delight, of your solace and consolation,
which is mixed with your adversity and suffering.

Howbeit my heart is often sad, and my spirit afflicted within me,
because of the many impediments and obstructions which
the Lord`'s truth meets withal in this country;
whereby it is much hindered from spreading and breaking forth:
so that I cannot say that it flourisheth and prospereth here,
as it hath flourished and prospered among you,
when the Lord`'s truth did so eminently break in upon you,
and his heavenly power did so mightily break forth among you,
to our refreshment in the Lord.
Yet verily I have no cause to complain;
for the wonted goodness and tender mercy of the Most High is perfectly continued unto me,
otherwise I should be much more bowed down than I am,
and that through the sense I often have of the body`'s suffering,
and of yours as members of it; and also of the subtle working of Satan,
together with other things of the like nature;
but the sense of the aforesaid goodness and mercy does support
me in all my travels and sufferings in the Gospel.
And I doubt not, my dearly beloved,
but that you have the sense of the same to support and uphold you,
in all your manifold afflictions and tribulations.

Well, therefore, be patient and content in the will of the Lord,
without willing anything, but that his will may be done in all things;
lest while you should will to have things thus and so,
and after this manner or the other, you should be found out of the will of the Lord,
and among them that are willing and running, and unbelieving,
to whom there is no true peace or rest.
But I hope God, of his infinite mercy, will establish your hearts in faith and peace;
that you may depend wholly upon his power and mercy,
which hitherto upon all occasions we have found sufficient:
to this then will I commit you all, my dear friends;
and in the sense and virtue of the same,
do I dearly greet and salute you all with love unfeigned in our Lord Jesus Christ.

I suppose that some of you have heard of my being lately in Friesland;
where there was but little entrance to be gotten for the truth,
and therefore was my refreshment the less, and my sufferings the more.
Howbeit some few I found, and but few, in their metropolitan city,
who with a ready mind received my testimony.
When I had been there some time, I returned again to Amsterdam,
where we are much more visited with strangers in our
meetings than in any other place in this country.
And as concerning the plague there, it is, through mercy, very much abated;
so that there died the last week but about one hundred and eighty-six,
which is about the ordinary number that used to die in a week:
howbeit the city is not yet free of the sickness; for the same day I came from thence,
I was to visit a Friend that was exceedingly ill of the plague,
and two of his children are lately dead of the sickness,
with another young man that lodged in his house.
So that whom the Lord is pleased yet to visit with it, he visiteth;
and therefore none can assure himself of being
freed from it longer than the Lord pleaseth.

About the latter end of the last week, at and about Amsterdam,
there was a multitude of trees, small and great,
that were so admirably rent and broken and bowed down by ice that was frozen upon them,
that it was very wonderful to behold; surely it was a figure to that lofty city,
and to the inhabitants of it,
who are like unto those whom the prophet compared to the tall cedars of Lebanon.
Here hath also been a strange comet seen for some weeks by many in these parts,
which signs and tokens, as also the late visitation of the plague,
together with the present threatening war, cause many to muse, and some to believe.
Yet the Lord is determined to bring yet greater judgment upon this land;
and it may be that when the vial of the Lord`'s indignation shall be poured forth,
then the day of the Lord`'s gathering shall be.
This day I have seen their weekly news,
in which they have made mention of our seven Hertford Friends,^
footnote:[See [.book-title]#Sewel`'s History#, under date of 1664.]
that were ordered to be sent away,
showing that neither wind nor weather would serve the ship so that she could sail.
And when the master could have no success with them, he put them ashore,
that he might accomplish his voyage the better, etc.
This even makes our enemies imagine,
that the hand of the Lord is against our persecutors,
in their proceedings against Friends.
I have lately visited most Friends in this country, and they are pretty well,
blessed be the Lord; and their dear love is to you all, and for any thing I know,
their small meetings are for the most part pretty peaceable.

Often am I, with other Friends, truly sensible of your manifold sufferings,
and a perfect sympathizing we find in our very hearts with you;
and we doubt not but you are sensible thereof.
And truly we are right willing, not only to share with you of your consolation,
but also to partake with you of your tribulation.
So read ye our love, desire and willingness, and compare the same with yours,
and you shall find that we are like-minded with you, yea of one heart and soul,
and members of one body with you.
And in this union and oneness we suffer and
rejoice with you;--and in the one eternal Spirit,
by which we are united, do I remain, as in months past, your dear brother and companion,

[.signed-section-signature]
William Caton.

--

[.offset]
The following are extracts from the latest original letter of William Caton`'s,
which the Editor has been able to discover.
It is dated "`Amsterdam, 19th and 20th of the Eighth month,
1665,`" and is addressed to James Moore, woollen-draper, Kendal.

[.embedded-content-document.letter]
--

I give you to understand, that through the infinite mercy of the Lord we are very well,
and our meetings continue unmolested;
except sometimes among the many strangers that resort to them,
there may be some contentious or light person, who may seem to be a little troublesome.
But I must confess we have no just cause to complain,
having no greater suffering than our sympathizing with our
suffering brethren in England in their grievous sufferings.
O! that the Lord would be pleased, in this remarkable visitation,
which is upon that nation,
to break the hearts of them that are so inclined to persecution;--
that they might come to desist from all such destructive enterprises,
which are so exceedingly prejudicial, both to kings, kingdoms, and subjects,
as might largely be shown.
Methinks it is very commendable to see, as I have often seen in this city, Calvinists,
Lutherans, Papists, Baptists of divers sorts, Jews, Friends, Armenians, etc.,
go in peace, and return in peace, and enjoy their meetings in peace,
and all are kept in peace in the city, and that without any trouble to the rulers;
who I think have it manifold better,
and are much more at peace and quietness than the magistrates in England,
who first are troubled with making laws to take away liberty of conscience,
and then more than a little with executing those laws, etc.

I was glad to hear of the welfare of my friends and relations;
to whom I desire to be remembered,
and in particular to my sister Dorothy and her husband: and let them know,
how that I and my dear wife are very well, blessed be the Lord.
I desire that my dear love be dearly remembered to all our Friends and brethren;
also to Friends at Cartmel, Underbarrow, and about Hawkshead,
and at and about Swarthmore; in particular to dear Margaret Fell and her children:
and of my love to Yealand Friends in the truth I could say much.
I herewith commit you all to the protection of the Almighty--
and in love unfeigned remain thy and your dear friend,

[.signed-section-signature]
William Caton.

--

There is reason to believe that within two, or, at most,
three months from the date of this last epistle, William Caton was removed by death,
in Holland.
"`He died in the Lord, and is blessed; and rests from his labours,
and his works follow him.`"--from George Fox`'s Testimony concerning him.
