== _George Fox`'s testimony concerning_ William Caton

In the year 1663, William Caton went to Holland,
and not long after he had finished his testimony there, he died; and soon after that,
his wife died; and he left this journal of passages behind him, which being sent to me,
I thought fit to put it in print and to recommend it to all that knew him.
For after he was converted, he preached the gospel of Christ,
and strengthened his brethren;
and you may see he was one like to the converted scribes in the kingdom of God,
which bring forth things new and old.
He was like unto Timothy, who was an example both in innocency, simplicity and purity,
in his life and conduct, after he was converted; for they did preach,
as well as his doctrine, in the churches of Christ.
And whereas many have made a boast and a talk of Truth in the beginning,
who never knew what it was; in his narrative,
you may see both an example and a testimony of Truth in the beginning,
and how for many years he travelled many weary steps on foot, both in England, Scotland,
and elsewhere, in the Lord`'s service.

His innocent life preached both righteousness and truth
where he came and was a good savor to God,
and in the hearts of the people.
He was one who had a care of God`'s glory and honor,
and the spreading of the Truth and the prosperity of it;
and in it he spent himself and finished his testimony; who, in his life time,
wrote many precious epistles to Friends, besides several books.
In his travels he had many trials and exercises by false brethren, backsliders,
and apostates, besides his perils by the sea, and among the priests and professors;
but the Lord with his eternal arm and power gave him dominion over all.
And as for his opposers, they withered and vanished away;
and after he had finished his testimony, he died in the Lord, and is blessed,
and rests from his labors, and his works follow him.

[.signed-section-signature]
--George Fox

[.signed-section-context-close]
Gooses, +++[+++near Brentwood, Essex,
his son-in-law William Mead`'s house,+++]+++
14th of Sixth month, 1688.
