== Life of William Caton. Chapter I

[.chapter-synopsis]
* The infinite mercy of the Lord God to him from his very infancy
* How it was with him in the days of his youth
* His introduction into Judge Fell`'s family at Swarthmore.

The God of my salvation has been pleased of his infinite love,
to show mercy unto me from my very infancy unto this present day,
and has through a secret hand preserved me from many of the evils in the world,
which befall the children of men, and with which many of them are overcome.
Yes, from my very childhood has he dealt exceedingly gently, bountifully,
and mercifully with me,
and especially since he was pleased to make known his heavenly truth in me,
and his eternal salvation to me.
How should I therefore forbear to show forth his praise,
and to declare his wonderful works?
To the end, that others may learn to fear and know him, to serve and obey him,
that their souls may receive mercy from him as I have done,
and that they may praise and magnify him in the land of the living,--who is God over all,
the Creator of all things; to whom be glory, honor, and dominion forever and ever.

When I was a child I was nurtured and tutored
with such fatherly care and motherly affection,
as my parents at that day were endued with.
While I was yet very young, my heart was inclining to wisdom and understanding;
and being inspired with a divine principle, +++[+++the Holy Spirit+++]+++ I did in
those days sometimes feel the power of it overcoming my heart,
and begetting tenderness in it towards my Creator,
when I have stood musing upon his handiwork.
And by attending to this divine gift,
I was much restrained from some vices to which children are prone.
But, alas, I knew not that that which restrained me was within me,
though I had a dread and fear upon me when I was liable to sin against my Creator;
which now I know right well, came through the aforesaid measure of His Spirit or light.
I had also a fear upon me of reproof and chastisement from my parents,
who according to their knowledge endeavored to educate me in virtue and godliness;
and therefore instructed me to pray morning and evening, to read often,
and to go frequently to hear that which they called the _Word of God_.
Great was their care to bring me up in the fear of the Lord,
according to their ability and understanding,
as also in "`good fashion,`" as they called it, in the world;
and therefore they educated me in such schools as the country there afforded,
and that for many years.

When I was about fourteen years of age, my father took me to Judge Fell`'s,
to learn with a kinsman, a priest, who was preceptor to the aforesaid judge`'s son;
and thereby I came to have an opportunity to be
conversant with them that were great in the world.
And through the mercy of the Lord, I behaved myself so well among them as to the outward,
that I found favor among the whole family, even from the greatest to the least of them;
and was in due time promoted to be a companion night and day to the judge`'s son,
and did eat as he did eat, and lodged as he lodged,
and went after the same pleasure which he went to, as fishing, hunting, shooting, etc.
In that day my heart was affected with my condition;
forasmuch as Providence had cast me into such a noble family,
where there were such sweet children,
with whose company I was more than a little affected; and in as much pleasure,
ease and fulness, I lived with them, as my heart could well desire.
There remained an integrity in my heart towards God, and often did I call upon his name.
To that end, I would linger in the chamber, until the judge`'s son, with whom I lodged,
had gone down, that afterwards I might go to prayer alone;
for my soul desired to have the blessing and favor of the Lord,
in which there was satisfaction to be found, but not in the pleasures which I followed,
nor yet in the ease and fulness in which I lived.

After we had learned some time together in the judge`'s family,
we were removed to a school in the country, at a place called Hawkshead;
where I met with many temptations, and seldom good company,
but such as were given to folly and wantonness.
But the Lord was wonderfully gracious to me;
and many times when I have deserved nothing but stripes from him,
has he broken and overcome my heart with his divine love;
so that I often stood admiring his wonderful mercy, his long-suffering, forbearance,
and infinite goodness.
For truly had his compassion failed, I might have been destroyed in the sins of my youth;
but blessed be his name forever, he had mercy on me.
As Providence ordered it, we did not stay long at that school,
but returned to Judge Fell`'s, where it was with me as before mentioned,
so that I began to see into the depth of what the world could afford.

Being then about fifteen years of age, my heart was much inclined after wisdom,
as also to seek knowledge; for in that family there was a great profession,
and such as could speak of the Scripture, and could make repetitions of sermons,
and paraphrase thereupon, were held in esteem.
Therefore I endeavored much to retain the heads thereof,
but when my memory would not serve me to do as some did in that particular,
I used myself to write much after the priests.
But that which I reaped thereby, could not give satisfaction to my soul,
which at times hungered much after the Lord.
