== Chapter IV

[.chapter-synopsis]
* 1655--He travels with John Stubbs into Kent
* They reach Dover, are brought before the Magistrates
* Luke Howard
* His boldness in their service
* They proceed to Hythe and other places
* Are cruelly treated at Maidstone.

We stayed some time after this in the city, where we had good service for the Lord;
and afterwards it was upon us to go into Kent towards Dover, which accordingly we did,
upon the 13th day of the first month, 1655, in much weakness and fear,
we being but young in the truth, and hearing of such wise professing men in those parts.
Howbeit, in the faith we went on, having confidence in God, who had been with us,
and who was with us.

In due time we got to Dover, where we were as pilgrims and strangers,
not knowing the face of any in the town.
After we had walked awhile in the streets,
being very much pressed and burdened in our spirits,
we took up our lodging at an inn or ale-house; where we had been but one night,
when the mayor came to us, having heard something of such men being in town,
and he examined us: it being on a first-day in the morning,
he would have had us secured for that day, but having nothing against us,
he could not well bring his purpose to pass.

After he left us, it was upon me to go to the steeple-house,
where I had but little liberty to speak before I was hauled out;
but in the yard I had some more liberty to clear my conscience to the people.
As for my dear companion John Stubbs,
he was at the same time at the meeting of the Anabaptists, so called.

In the after part of the day, he was at the other steeple-house,
and I was moved to go up to the castle to the meeting of the Independents, so called,
so that by that day`'s service the report of us went not only through the town,
but also into the country, and of the truth of which we bore testimony.
Shortly after, we had liberty to have a meeting in the Baptists`' meeting place,
to which many people resorted; and the Lord was with us, and gave us mouth and wisdom,
not only powerfully to declare, but also zealously to contend for the everlasting truth,
which was then much opposed and spoken against both by professors and profane: howbeit,
some began to adhere to it, and to be affected with it,
and then did the enmity begin to work in the hearts of the people against us.
We were hauled before the magistrates, who examined us,
and did use much means to get the town cleared of us,
and ordered that none should entertain us upon a certain penalty;
whereupon we were turned out of our lodging.
But the Lord raised up one Luke Howard, a shoemaker, who had become so loving to us,
and so bold and valiant, that he undertook to entertain us in his house,
notwithstanding their order; where we abode several days,
and had afterwards a meeting or meetings in his house;
and several at that time came to be convinced of the truth,
whom we commended to the grace of God and left them.

[.small-break]
'''

+++[+++Editor`'s Note: The following account is given by Luke Howard in his Journal,
of his first meeting with William Caton, and of his visit to Dover.
After describing the bewildered state of his own mind,
and that he could find no trodden path, and no man to lead him out of the wilderness,
Luke Howard informs us, he went up to London in 1654-5;
and on a first-day he went to hear "`one Cardwell, in Lombard street.
When he had done, there stood up a young man newly come out of the north country,
his name was William Caton; who sounded an alarm out of Zion,
and proclaimed the gospel of peace.
"`At that time it seemed to me like the priest`'s preaching;
my mind then being more abroad after visible things, than within after invisible:
which made me say to my companion,
'`Come, let us be gone to dinner,`'
(not staying till he had done;)
'`for I know as much as he can tell me, or more than I or he either can live in;`'
thus making myself a judge of his life and doctrine,
which I knew not: and so I turned my back upon the truth, as too many do.`"

"`The after part of the day we spent our time in walking in the fields;
and the week following I got home.
The next first-day afterwards, one meets me in the street,
and tells me there was a Quaker preaching in the churchyard,
who was the same aforementioned William Caton.
At which I immediately went to see what manner of man that Quaker was:
and when I saw him, my heart smote within me,
and I was more reached with his bare person in Dover,
than with his person and words too in London.
And I was made a safeguard to him from the boys and rude spirits that offered him abuse.
When he had borne his testimony, he passed away.
I then took notice where he went in, and at night, Nicodemus-like, I went to see him:
I was reluctant to go in the day,
and would much preferred to have got company to go with me, but could not,
so I went alone; and then met with him and his dear companion John Stubbs,
who had been at the other steeple-house.
I believe the Lord stirred me in my mind to go to see them.
I found them eating a little bread with beer, without anything to sweeten or relish it.
So I asked them to go out with me;
and we went to a professor`'s (Baptist,) who conversed with them much,
and agreed to have a meeting the next day in the Baptist`'s meeting-house,
which was performed;--After which many followed them to their inn,
as wonderers and gazers, and some to oppose.

"`Then the rulers of the town sent to the innkeeper to turn them out of his house,
or else they would pluck down his sign.
So the innkeeper spoke to me, because he saw that I most took their parts,
and desired me to tell them, which I did: but I also said to John and William,
'`Go home to my house, for I care not for the rulers or mayor either.`'
So they went with me, and the fifth-day following we had a great meeting at my house:
and their testimony was to me as John the Baptist`'s was to Herod, who heard him gladly,
and as Paul`'s was to Agrippa, who was almost persuaded to be a Christian.
I was convinced in my judgment, and their testimony was to me as a pleasant song:
so the meeting ended, and all passed away in quiet.

He then describes his refusing to give up these Friends,
when applied to by the constables sent to his house by the mayor, etc.

"`The next day at my house again, we had a good and blessed meeting I may say;
in which these words were delivered:--that notwithstanding men`'s profession of religion,
the body of death is yet standing in them.`"
He then states that the witness within was answered,
and he became sensible of his own dark condition and state of mind;
so that it seemed to him to be the Lord`'s work to show me myself,
and that I was but death and darkness, and to empty me thereof;
that so he might fill me from his own fulness of grace and truth,
even the life of Christ Jesus, in whom alone he is well pleased.
Then did my two friends and fathers in the truth pass out of town,
and I went two or three miles with them;
and they took in writing the names of some towns and men along
the sea-coast:--and all whose names I gave received them;
at which time Samuel Fisher was one.
After I left them, my sorrow was great, and my tears many;
so that I had much ado to get and keep my eyes dry,
when I came back to Dover.`"+++]+++

[.asterism]
'''

[.emphasized]
+++[+++The following letter copied from the original,
found in a valuable private collection of letters formerly from Swarthmore,
may also be interesting to the reader.+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
John Stubbs and William Caton to Francis Howgill and Edward Burrough

[.salutation]
Dear hearts, Francis and Edward,

We came into Dover upon the seventh-day in the last week, being the market-day,
towards night, and passed to and again through the streets and in the market place,
though we had nothing given us to speak there; then at night we took up a chamber,
and we were known to no man by face.
The next morning the mayor and some of his attendants came to our lodging,
and examined us from where we came,
etc.--he was much troubled that we did not bow to him,
and said we should be secured as vagrants.
Then we were brought before a captain, who is one of the separate teachers;
he with this mayor was very exact in examining us severally;--
they asked us for letters,--we had papers,--they saw them,
and gave us them again.
We had our liberty with a charge from the mayor that we should be of good behavior.
After our departure from them, one of us went in the forenoon to a steeple-house,
and the other to a Baptist meeting.
William was pulled down in the steeple though with little violence,
but had his liberty to speak in the yard.
I had as much liberty among the Baptists as I could desire.
I saw a seed among them: a few words were spoken;--great was the power that attended.
In the afternoon, William went to the castle where the garrison is,
and there the captain was much opposite, but the soldiers were willing to hear.
I went to a steeple-house of Independents:
here are many high airy spirits as ever I met with, both in the fort and in the town.
Oh! Who is sufficient to encounter with such a generation!

There was a captain in that Baptist meeting and his wife,
who sent for us to their lodging upon the first-day at night, and some others were there.
There is a convincement upon them both, but especially upon him;
he commands a castle between this place and Maidstone, and is a very moderate,
plain-hearted man; he was very attentive at the meeting when I was there.
There come frequently from the castle and from the town to our lodging some
rich and some poor;--pray that we may be kept in the discerning state.
This day the post-master told us they desired to have a private meeting with us;
there is something kindled among them; the man is of a temperate spirit,
and very hopeful.
Another, a shoemaker, one Howard, who has been a Baptist,
(and his wife,) as he says these ten or eleven years,
but has no rest,--he is clearly convinced.
A fire is kindled among them, which cannot be suddenly quenched.

They are rich and very full, and now they are afraid to come to a loss;
we shall endeavor to get a meeting among them, and so clear our consciences to them.
Let us hear from you as shortly as you can,
and we would have you to send us a dozen of some sorts
of books which you think would be serviceable,
and we shall endeavor to get money for them.

You may direct them to be left at Luke Howard`'s, the shoemaker, in Dover,
to be conveyed to us.
The post-master is loving towards us, but we are at an inn in the town,
where many are free to come to see us.
So our dear love to all our dear friends with you.

[.signed-section-closing]
We remain your brethren, etc.

[.signed-section-signature]
John Stubbs, William Caton

[.signed-section-context-close]
Dover, 19th of First month, 1654

[.postscript]
We would have you to show this to George. _(doubtless George Fox.)_

--

After that we went from there to a town called Folkestone
where we were kindly received by Thomas Nichols,
his wife and others,--and some good meetings we had there;
the priest of the town and many others being present at some of them:
and the witness of God was truly reached in some, and some were convinced of the truth,
and received it in the love of it.
I was also at their steeple-house,
but was uncivilly treated and permitted to speak but little,
until I was turned out violently by a rude fellow;
but some that were simple and moderate were troubled thereat.

When we were pretty clear of that town, we travelled towards Hythe,
and in our way there we went into a castle which stood by the sea-side,
+++[+++Sandgate Castle,+++]+++
where we were kindly received both by the captain and his wife.
We had a meeting or two among the soldiers and others,
and after that we went to the aforesaid Hythe.
It was upon us to go to their public place of worship, which we did;
but soon after one of us began to speak, we were violently dragged out, but preserved,
through the hand of the Lord, from being much harmed by the rude multitude.

It was much noted that he who was the most violent against us,
had afterwards in a short time, some remarkable judgment which befell him.

In that town the Baptists allowed us the use of their meeting-room,
and at the first were pretty moderate and civil to us,
but afterwards they became (or some of them) our great opposers;
howbeit there were some in that place who believed and received our testimony.

We went from that town further into the country, and were at Romney and Lydd,
where there were many high professors, and among the rest Samuel Fisher,
a very eminent and able pastor among the Baptists.
It was upon me to go to the meeting of the Independents, and upon my dear brother,
to go to the meeting of the Baptists, where he had good liberty.
The aforesaid Samuel Fisher had been speaking among them, but, as it appeared,
was so much affected with John`'s doctrine, that after John had done,
Samuel began with his wisdom to paraphrase upon it with excellency of speech,
thereby to set it forth in his apprehension beyond what John had done.
At the meeting where I was,
they would scarcely allow me any liberty to clear my conscience among them.
After that, we had meetings in both places;
and being one time at a meeting in the street at Lydd,
for the Friend`'s house would not contain the multitude, the magistrates, or some of them,
sent to the aforesaid Samuel Fisher, who was also present at the meeting,
to tell him that we might have the church-door, as they called it, opened to go in there,
but we refused to accept of it, and chose rather to continue our meeting in the street.
The aforesaid Samuel Fisher believed our report, with several more in those two towns,
who were convinced of the truth of God,
which had not been declared in those parts by any Friend before.

We were also up in the country about Ashford and Tenterden, and had great meetings,
and strong contests with professors, who did much oppose us,
especially in those two towns;
howbeit we found some who were simple and
tender-hearted in most places where we got meetings.
We were also at Cranbrook and Staplehurst, where we found a very open people,
who were very ready to receive, and to embrace the everlasting truth,
which we freely and powerfully, according to our measures received,
administered unto them, in the demonstration of the eternal Spirit;
and several large and precious meetings we had among them,
and the power and presence of the Lord God were much with us,
in which we rejoiced together, freely distributing the Word of life unto them,
which at that time dwelt richly and plenteously in our hearts;
and as we had received it freely, so we did dispense the same freely.
For though there were those that would have given us both gold and money,
which some would even have forced upon us,
yet we had not freedom to receive one penny from them;
for we told them it was not theirs but them which we sought.
Many were convinced and much affected with the truth,
which with joy and gladness they received.
Among them, as at other places, we sought to settle and establish meetings,
and to bring those that were convinced to wait upon the Lord in silence,
in that light of life in themselves, which we turned them unto;
to the end that they might enjoy the substance of what they had professed.
Accordingly meetings came to be settled in most of the places before mentioned,
which they that were convinced kept up after our departure.

[.offset]
+++[+++Editor`'s Note:
Dover Friends were among the first that set this
noble example of gathering in the name of Him,
who promised to be in the midst of them,
and who was found to be the faithful and true witness unto them.
Of this, Luke Howard wrote as follows:

"`I may also acquaint you a little how things were with
us in our first convincement and meetings,
after we came to sit down to wait upon the Lord in silence;
which was our practice for some years, except when some travelling Friend came among us.
I can truly say, the Lord was our teacher,
and his presence and power were manifested amongst us,
when no words have been sounded in our outward ears: for several of us,
and at several times, in these meetings, have felt the power of the Lord,
that has made our outward bodies tremble as well as our hearts:
and great fear and reverence took hold of my heart;
and the Lord confirmed his truth in me from day to day, and answered my doubts,
and settled my faith by and in his power.`"--Luke Howard`'s
[ .book-title]#Collection of Writings,# 1704, p. 29.+++]+++

[.offset]
Returning to journal:

After that, we were moved to go to a great town called Maidstone;
and it being on a first-day of the week,
we were in the forepart of the day at a meeting
of the people called Baptists in the country;
and after we had declared the way of salvation among them,
we left them and went to the town aforesaid.
When we came there, it was upon my dear brother John Stubbs,
to go to their public place of worship,
and it was upon me to go to the meeting of the Independents, which accordingly we did;
and John was taken at their steeple-house, and I the day following at my inn,
and were both sent to the House of Correction, so called, where we were searched,
and had our money, and our ink-horns, and Bible, etc., taken from us;
and afterwards we were stripped, and had our necks and arms put in the stocks,
and in that condition were desperately whipped;
and afterwards we had irons and great clogs of wood laid upon us,
and in that condition they would have compelled us to work, saying,
he that would not work should not eat, etc.
Forasmuch as they had dealt so wickedly with us, and that without any just cause,
neither could they justly charge us with the breach of any law,
we were not free to consent so far to their cruel wills as to do their work;
and therefore they kept us without victuals for some days,
only a little water once a day we had allowed us: he that committed us,
and was the chief agent in cruelty against us, was a noted Presbyterian.
And though the malefactors that were there, would have given us of their bread, yes,
the women of the house being moved with compassion towards us,
would have given us something privately,
but we were not free at that time to accept of either,
until they by whose order the provision was kept from us,
gave consent that it should be brought in to us; which finally he or they did:
many in the town began to be offended at their cruelty, which they manifested towards us.
And when they, who sought to bow us to their wills, were made to bow by the power of God,
we were free to receive victuals for our money, and did eat and were refreshed.

[.offset]
+++[+++Editor`'s Note: The following particulars, in addition to those given above,
are obtained from some early records of Friends of East Kent.

"`William Caton being brought before the magistrate, was examined where he dwelt,
and how long it was since he came from his outward being, and what way he came;
with more of the like questions.
William answered, he came from London.
The magistrate asked what he did while he continued in London?
William said, in making known the everlasting truth, as he was moved of the Lord;
turning people from darkness to the light; that with the light they might see themselves,
and be brought to repentance, etc.
Then the magistrate told him, he had a master for him, and that he should be set on work,
and be bound unto him for so much a year, etc.
But William refused to be bound to man, or to be in bondage to any; saying,
he was in the work and service of the Lord,
and could not go out of the Lord`'s service to be a slave to man.`"

This early record then describes their cruel treatment
in nearly similar terms as in the journal above,
though sometimes more minutely.
After being sent out of the town they passed into the hands of many constables,
William Caton being separated from his friend.
The account then states, that these officers began to grow careless of their order;
and at length left them in the highways;
their heavenly countenances and sober lives and words preached so much to them,
that they finally allowed them to travel alone where they pleased.
The record continues to give account of their returning to Maidstone, etc., and adds,
"`before they got to Dover again,
the report of their wicked usage at Maidstone came to the ears of the mayor of Dover;
who meeting with Luke Howard, said, '`Luke, I hear your friends have been at Maidstone,
and been whipped: we did not deal so badly with them here.`'
'`No,`' said Luke Howard, '`but you dealt with them worse than you should.`'
So in a little time came William Caton and John Stubbs again to Dover, where they,
with Friends, enjoyed their meetings peaceably:
many being convinced.`"--Manuscript of Friends of East Kent.+++]+++

[.offset]
Returning to journal:

The next day following, after their cruelty seemed to be abated, they sent an officer,
who made restitution of some of our things again which they had taken from us,
but burned several good wholesome papers and letters.
Afterwards they parted us, and with officers conveyed us out of the town,
one at the one end of it, and the other at the other,
which was no small trial to us to be so separated.
We were conveyed from one officer to another in the country,
and in that manner sent towards our habitations in the north:
but when I had been in the hands of about twelve of them,
they began to grow careless of their order, and finally, allowed me to travel alone,
which accordingly I did towards London.

The day following I got well up to London,
where I was more than a little refreshed with the brethren;
and there I met my dear companion John Stubbs again to our great refreshment.
It came presently upon us to return to the town of Maidstone again,
and into that country, which was no small trial to us; however,
to the will of the Lord we gave up, and returned within two or three days.
When our grand persecutor at Maidstone heard of our return, he sent a party after us,
and it being come eight miles into the country,
the officer came into a Friend`'s house where we had lodged;
but were then at another place; and it being on a first-day,
in the morning we went to their steeple-house, but the officer was not then there;
and Providence did so order it, at that time we were preserved out of their hands.
Afterwards we passed through the country visiting the
brethren that had received the gospel,
who were confirmed in the faith, and the more so through our patient suffering.
We were also at Canterbury where we had good service,
especially among the Baptists and Independents so called; for we were at their meetings,
and had pretty good liberty to declare the truth of God among them,
and some there were that received our testimony in that place also,
who were convinced of the truth, so that there came to be a meeting settled there.
We were likewise at Sandwich,
where I had some service in particular among the Dutch people at their steeple-house,
but at that time the truth could get but little entrance in that place.
