== Chapter VII

[.chapter-synopsis]
* 1656+++.+++ Attends a general meeting in Leicestershire
* Again visits Scotland; has good meetings at Edinburgh, Leith, Stirling, etc.
* Returns to Swarthmore, and proceeds to Bristol and into Cornwall
* Visits George Fox in Launceston jail.

About this time, as I remember,
I took a journey into Leicestershire to a great general meeting which was appointed,
to which many of the brethren resorted, and among the rest there was dear George Fox,
whom I much desired to see.
A very precious meeting it was;
and afterwards I had some precious time with the brethren, and took my leave of them,
and returned again into Lancashire.
I had not been long there, when it was upon me to go into Cumberland and Scotland again;
whereupon I took my leave of Friends in those parts, and went towards Cumberland:
and on the 4th day of the third month, 1656,
I was at a meeting at Ambleside close by the chapel,
and several of the people were with us after the priest had done.
In the afternoon I was moved to go into the chapel among them,
but they were exceedingly violent against me, and seemed to thirst much after my blood,
for they fell upon me, as if they would have torn me to pieces;
but their power was limited, and I was preserved in the arms of the Lord,
and endued with much courage and boldness to declare the everlasting truth among them.

Afterwards I went into Cumberland,
where I had several good and precious meetings among Friends,
to the confirming of them in the truth, and to my great refreshment in the Lord.
When I had visited Friends in that county, I took my leave of them,
and went from there to Scotland again,
being accompanied by a dear brother called John Grave.
We travelled towards Douglas, where we visited the few Friends that were convinced,
and had a meeting in the steeple-house yard,
where many heard the truth declared in the power and demonstration of the Spirit,
especially in the priest`'s absence; but when he was at his devotion many of them left us.
In the steeple-house, when the priest was catechizing his hearers,
and sometimes when they could not answer him, I was ready to reply,
and I gave him some queries to answer: and sometimes he said he would answer them,
and sometimes he said he would not;
but finally he broke out into a very great rage and passion,
and caused the people to turn me out of my lodging;
and it is possible he would have done much more, if he had had power.

We travelled from there to Edinburgh, where we had several good meetings,
as also at Leith, and that openly in the street; many resorted to them,
both of the English that were in that country, and also of the natives:
so that many precious opportunities we had of declaring the
everlasting truth of God freely and powerfully among them.
About that time I was not well in body, having oppressed it with sore travel;
howbeit the Lord was pleased to restore me again in a pretty short time,
even for the service sake.

When we were pretty clear of Edinburgh and Leith, we travelled towards Stirling city;
but when we came there, the people were so incensed against us,
that we had very much to do, to get lodging for our money,
which finally some soldiers procured for us.
When the first-day of the week came, it was upon us to go to their great steeple-house,
which accordingly we did;
and being there at the very time when the priest was
going about to swear some of them upon some occasion,
I was moved to speak, and tell them that Christ, the head of the church, said,
"`swear not at all;`" but little more would they allow us to speak in that place.
Afterwards we were carried before the governor, who was pretty high against us,
and would even have forced us out of the city; howbeit he was then prevented,
for the Lord had a very considerable service for us in the afterpart of the day.

We had appointed a meeting upon a green, near the steeple-house,
to which a great concourse of people resorted;
and a very precious and serviceable meeting we had,--for the Lord was pleased to
give us his word plentifully to communicate to the people freely and powerfully,
and his presence was with us, and his living witness was reached in many,
which testified to the truth of what we declared;
and little further opposition did we meet with at that time.
Yet some of the people were so envious, and others fearful,
that many of them dared not entertain us;
neither could we well get lodging in the city that night;
so we went out into the country, and not without difficulty could we get lodging there;
for the Scots were prejudiced against the English,
they looking upon us as if we had been some straggling soldiers,
were therefore the more afraid of us; yet Providence did so order it,
that we got well through the country to Glasgow.
When we came there, we found the governor, one Colonel Ashfield, a very moderate man;
and he sent for me to his house, and reasoned very moderately with me, as also his wife,
who is since convinced of the truth, and he is very loving to Friends;
his chaplain was also friendly to us.

When the first-day of the week came, it was upon us to go to one of their steeple-houses,
which accordingly we did.
When the priest had finished, I began to speak to the people, but the drums beat,
whereby the soldiers were called away;
and as for the Scots they could not endure sound doctrine,
but turned away their ears from hearing the truth.
At this city I was carried to the main-guard,
where I had good service among the soldiers, who were very civil towards me,
and in due time they allowed me to depart in peace to my lodging.

When we had had very good service in that city, and were pretty clear and free of it,
it was upon me to go to another noted place called Ayr, in the west of Scotland,
and it was upon my dear companion John Grave, to go to another place,
so that we parted for a season,
which was no small trial to us in that dark and barbarous country.
In due time I got to Ayr; and it was upon me to go to the steeple-house there,
where I had pretty good liberty, there being many soldiers,
and I was civilly treated among them.

After I was clear of that place and others, according to the will of God,
I set my face again towards England,
and travelled many a mile alone in that barren and rude country;
howbeit the Lord was with me,
and through his mighty power I was not only
preserved out of the hands of unreasonable men,
but also through his mercy, from the sin and evil which abounded among those people;
for which my soul has cause to bless and magnify the name of the Lord,
while I have my being.

In due time afterwards I met with my dear companion to our mutual refreshment;
and then with cheerfulness, after we were clear of that country,
we returned to England again.
When we got into Cumberland we had very large and precious meetings,
even as we had had before our going into Scotland;
and Friends were strengthened and confirmed in the precious truth,
which in those days did flourish and prosper very much;
and the Lord`'s power and presence were with us,
through which we were carried on in his work and service,
in which our souls delighted to be exercised.

After I had had good service, in Cumberland, I visited Friends in Westmoreland,
and in due time got well back to Swarthmore again,
where I was dearly received as in months past; after my great travels,
I always found it a place of refreshment to me, both for soul and body.
But I was not permitted to stay much,
there being such an effectual door open abroad in the country;
and therefore I was constrained, through the love of God which dwelt richly in my heart,
to labor so much the more diligently,--for I knew it was good working while it was day.
When I was at Swarthmore, we had not only many precious meetings there,
but also several in the country thereabouts, near to the steeple-houses and chapels:
so that many heard the truth of God plentifully declared,
both of them that believe and of them that perish; and, indeed,
a glorious and precious time we had, to make known unto people the way of salvation,
and what the Lord had done for our souls; many believed and were converted,
and brought to serve and worship the Lord in spirit and in truth.

I had not been long in those parts when it was upon me to go towards Bristol,
and further westward so far as Cornwall;
whereupon I took my leave of Friends at Swarthmore in abundance of love and tenderness,
in which we were accustomed to meet and to part, and travelled with a dear companion,
whose name was Walter Clements.
Many brethren and Friends we visited in our journey to their and our comfort;
and in due time, through mercy, we got well to Bristol,
where I was more than a little refreshed with Friends,
to see how the truth prospered among them, and what large and living meetings there were,
both in the city and also in the country thereabouts.
I was moved to communicate freely to them of the
overflowing of the life and power dwelling in me,
which tended to the comfort of many.

After we were refreshed together in the Lord I left them,
and went on my journey westward,
for I was determined to visit some of the brethren that
were in prison in Launceston jail in Cornwall.
I visited several Friends as I went, travelling mostly alone and on foot also:
but the Lord was with me, and through his goodness I got well to my journey`'s end;
where I was not a little comforted with the brethren.
I went out also into the country, where I had some very good service;
and afterwards returned to the prison again, where my refreshment was so much,
that my cup was even made to overflow,--there being at that
time dear George Fox and several other Friends prisoners there:
of whom in due time I took my leave, even in the fulness of endeared love,
and returned again out of those parts.
