== Chapter XI

[.chapter-synopsis]
* 1653+++.+++ Travels to London
* His labors in Kent, Sussex, etc.
* Proceeds to Bristol, and returns to London
* Attends a General Meeting of ministering Friends at the Bull and Mouth (1659)
* Sails again to Holland and returns
* Dangers on his voyage back.

About the latter end of the Sixth month, 1658,
I took my leave of that honorable family +++[+++at Swarthmore+++]+++
and of Friends thereabouts, and set my face southwards again,
visiting Friends in some part of Lancashire, and especially in Cheshire,
where I stayed about a week or more,
and had several good and precious meetings to our great refreshment in the Lord.

Afterwards I went pretty readily to London, where I found several of the brethren,
and an effectual door open, and Friends generally well, fresh, lively,
and very open and tender: and I had good service in the city,
and the Lord was pleased to give much dominion,
and even fulness to me out of the everlasting treasury, which,
through him that strengthened me,
I freely communicated to them whose souls were breathing after the Lord.

[.embedded-content-document.letter]
--

[.letter-heading]
William Caton to Margaret Fell

[.signed-section-context-open]
London, 13th of Seventh month, 1658

&hellip; I came into the city, and my soul has been much refreshed among the brethren.
Here is a mighty door open at present in this city; and Friends are generally fresh,
lively, and tender: and for the generality of the people, they are much under,
and many are moderate and loving, whose hearts are open to receive the truth.
I have had as good a service in the work of the Lord, since I came to this city,
as I believe I ever had in my life.
Upon the first-day, I was at the meeting at the Bull and Mouth,
where the Lord was pleased to open the hearts of many,
who with joy and gladness received that which the Lord allowed me to speak;
so that in much love and tenderness I left them.
After that meeting I passed a mile out of the city, when I had a very precious meeting,
which consisted of a great concourse of people,
several captains and masters of ships and seamen, with other persons of note and quality,
who were generally very moderate and open to receive the truth.

After that meeting was ended, I returned again into the city to another meeting,
where the power and presence of the Lord was made manifest to the
great refreshment of the most part of the Friends then assembled.

--

[.offset]
Returning to Journal:

When I had been about two weeks, or above, in and about the city, I went down into Kent,
where I also found an open door, and fresh desires in people after the Lord;
and many precious meetings I had also in that county,
which were of great service for the establishing
of Friends in the truth who were convinced,
and for gathering in of others, who were hungering and desiring after the truth.

I went out of that county into Sussex, where I also visited Friends,
and had several precious meetings among them;
and travelled along pretty near to the sea coast, so far as Southampton,
where I had also good service among Friends;
and after we had been plenteously refreshed together,
I took my leave of them as in other places, and visited Friends at Winchester,
who were in prison.

Afterwards I travelled westward into Somersetshire,
where I visited Friends and some of their meetings;
and being sweetly refreshed among them, I went to Bristol, where I had good service,
as also in some parts of the country thereabouts among Friends;
and it was no small matter of joy and rejoicing to me
to see the truth of God prosper and flourish,
as I saw it did in that journey.
In due time I returned to London again by Reading, where I also visited Friends,
and reaped refreshment; for in all those travels the Lord had been with me,
which even made them, together with the service which I had in them,
very pleasant and delightful to me.
Many precious and peaceable meetings I had;
and the Lord gave me utterance in power and much authority,
to declare and publish his name and truth; all which redounded to his praise,
which was his due, and which my soul did freely render to him, who is the fulness,
itself, from which all my fresh springs flow.

After I had some very good service in London, I passed down into Kent again,
about the 20th of the ninth month;
where I had very precious service for the most part of a month,
and afterwards I returned to London again, where I determined to stay but a few days,
when I went there; but the work of the Lord was so great in it,
and meetings so full and so many,
that it was hard to get out of it again in a short time;
for in those days the truth did mightily prevail and prosper, not only in that city,
but in the country about, as also in many parts of the nation.

I spent some months in those southern parts,
where especially there was an effectual door open:
and oftentimes in great service for the Lord I was exercised both day and night,
in which the Lord made my cup to overflow.

At the time called Easter, +++[+++1659,+++]+++
there was a general meeting appointed, especially for the ministering brethren,
who resorted to it from several parts of the nation,
which was held at the Bull and Mouth, near Aldersgate in London,
upon the 5th of the second month, 1659: it was very large and exceedingly precious,
to the refreshing of many hundreds.
In the afterpart of the day we had a very great concourse of
people at our meeting place at Horsleydown in Southwark,
where, within and without doors,
it was thought some hundreds might hear the truth declared that afternoon,
with which many were much affected; and great was our rejoicing and comfort,
which we had in the work and service of the Lord,
in which we were abundantly refreshed together;
In that great assembly our souls even with one accord,
praised and magnified the God of our salvation; and in a few days after.
Friends departed out of the city again,
the end being fully answered for which they came together.

About that time it was upon me to go +++[+++again+++]+++
for Holland, and I took my leave of Friends and brethren in London,
and in much brokenness of heart, love and unity, we parted.
I took my journey towards Colchester, there to take shipping, which accordingly I did,
after I had had several large and precious meetings: but the wind being contrary,
I stayed there, and thereabouts near upon three weeks,
in which time I had very good service;
for the Lord`'s heavenly power and presence was much with me, as in other places,
not only to my refreshment, but to the refreshment of many more in the Lord.
When the Lord made way for it, I went aboard, and we set sail;
but the wind proving contrary, we put in at Harwich,
whereby I had an opportunity to see Friends there also.

On the first-day of the week, I had a large meeting there, to which many came,
not only many Friends out of the country, but also many people that were not Friends,
who seemed to be pretty much affected with the truth when it was declared to them.
When I had spoken about an hour or two, the master of the vessel came and called me away,
for he was determined to set sail: I committed them to the grace of God, and went aboard,
and probably thirty or forty Friends might follow me to the ship-side in boats,
such was their love, to the admiration of the spectators.

Through the good hand of God I got well over to Rotterdam, where I visited Friends,
as also elsewhere in the country.
I found things pretty well in reference to the truth, and meetings pretty peaceable;
and about that time strangers came more frequently to our meetings than formerly:
and if things had not been carried in much wisdom, we might have been often in tumults,
for there were those who watched for iniquity, and were ready to do mischief,
thinking that if the magistrates would not meddle with us, as we then were,
yet if they could but procure an uproar or tumult at or about our meeting places,
we should be punished as uproar-makers.
Notwithstanding the evil conspiracies of the wicked,
the Lord was exceedingly good to Friends,
and very gently and compassionately dealt with them; and they grew bold and valiant,
and the truth got dominion among them.
My suffering before had been great in that country,
especially before I could speak their language,
yet the Lord refreshed me much among that small remnant which were called by his name,
and who walked in his eternal truth: and having gotten their language,
and being able to minister in it,
I could much better free myself of the weights and burdens than before.
When I had stayed about two months,
and seeing things in a pretty good posture as to the truth,
Friends well settled, and their meetings kept in good order,
it was upon me again to return for England, where there was such an effectual door open.
I took my leave of Friends in Holland,
whom I committed to the custody and protection of the Almighty, and so left them.

In the latter end of the fifth month, 1659, I took shipping for England,
partly intending for London.
When we had been about twenty-four hours at sea,
we saw a ship which proved to be a pirate or robber, which chased us;
when the master perceived it, he caused all to be made in readiness to fight,
and the passengers that were aboard were furnished with arms as well as the rest,
but for my part I could not touch any of their weapons, as to shed blood with them,
but stood simply given up to the will of the Lord.
But as Providence ordered it, when they were almost within shot of us,
their hearts failed them, and they were not permitted to come up to us,
so that there was no blood shed, nor harm done to each other;
wherein the Lord answered my desire, for which mercy my soul did bless, praise,
and magnify his holy name.

After we were delivered through the good hand of
God from the hands of the aforesaid pirate,
we were in imminent danger through a very violent storm,
which took us when we were near the coast of England;
and coming to cast anchor we left both anchor and cable,
and had our boat split in pieces.
One great ship that rode by us was swallowed up of the raging sea--a
sad sight to behold--there not being one man saved alive in her;
yet nevertheless, the same God that delivered us from the hands of the aforesaid pirate,
did also deliver us out of that violent storm;
through whose mercy we got finally into harbor at Yarmouth,
though it was near a hundred miles from the place for which we intended.
