== Chapter XIV

[.chapter-synopsis]
* 1660+++.+++ He leaves Dover for Holland
* His service in several cities and places
* Returns to London (1661) but soon after revisits Holland
* He travels with William Ames into Germany
* At Heidleherg is courteously treated by the Prince Palatine.

About this time I passed towards Dover, where I took shipping for Zealand,
to go for Holland; and after some hardship sustained at sea,
by reason of tempestuous weather and contrary winds,
through the providence of the Lord I got to Flushing, where I stayed but little,
and passed for Middleburgh,
where I visited the very few Friends that there were in the city;
and afterwards I went to Treveare,
where I found a vessel almost ready to sail for Dort in Holland.
In my journey I was exceedingly filled with the Lord`'s love, and the power of his might,
though I was alone, not having any Friend in company with me, but many passengers;
and among the rest a Catholic, who was filled with much envy and wickedness,
and uttered desperate threatening words against me,
giving some to understand what a small matter it was in their account,
to do a man a mischief who spoke against their religion.
In the height of his wickedness he boasted of a pardon which he had in his pocket,
not only for the sins he had committed, but also for what he should commit:
but before we parted, the power of the Lord reached to his own witness in the man,
whereby he was smitten in himself for his folly,
and his fury against me was much turned into friendship towards me.
Thus do we often see the Lord changing the hearts of our enemies,
and restraining them from the evil they intend against us;
which we must acknowledge to be the Lord`'s doing, which is, and often has been,
marvellous in our eyes; to him therefore be glory, honor, and dominion, forever and ever.

I got well to Rotterdam, through mercy, where I found Friends very well in the Lord.
After we had been sweetly comforted together, I took leave of them,
and went to the city of Leyden, where I also visited that little flock,
with whom my soul at that time was comforted.
From there I passed to the city of Amsterdam,
where my refreshment was augmented in the Lord among his babes in that place,
at which I arrived the sixth of the tenth month, 1660.

Afterwards it was upon me with another Friend called Peter Hendricks,
to go into Friesland, which we did;
and in due time through mercy we arrived well upon a first-day in the morning,
at a place called Dockham, where we went into the meeting of the Baptists, so called,
which was very large.
When he that spoke had finished,
I stood up and began to declare the everlasting truth in their own language.
They were much divided among themselves, for some would gladly have heard me,
others would not allow me; but one of the chiefest of their teachers was very moderate,
and spoke to this purpose, that if I had a nearer way to God to declare,
than that which they knew, or one that was more excellent than theirs,
they would willingly hear me.
In order thereto many of them came together in the afternoon,
and heard me declare that way which I preferred before theirs,
and affirmed it to be nearer to God, and more excellent than theirs:
and little they had at that time to object against it.

Before we parted they were so far satisfied, that by their great silence,
in which they sat as if they had been Friends,
they seemed not to have anything further to object.
After the meeting was done, the aforesaid teacher invited us to his house,
and to take up our lodging there, which for several reasons we were free to accept of.
When we got to his house at night, many people followed us,
so that we had a very good meeting.
And when we had continued there some time in very good service,
we left that place and returned to Leuwarden, the metropolitan city of that province:
there we found some in whom there were desires after the truth,
with whom we had meetings.
Afterwards we passed to a place called Mackham,
where there were also many of the aforesaid Baptists,
and we were entertained by an old man, who had been a preacher among them for many years.

When first-day came, it was upon us to go to their place of worship, which we did;
and waited until he that was speaking had finished.
Afterwards I began to speak, but he would not allow me,
(that is, he that had preached,)
but became presently very angry,
though the people would gladly have heard me; but he would not permit them;
and he became finally so uncivil,
that he put the people out of the meeting place with his own hands;
at which some being much offended, a skipper or master of a vessel, stood up and said,
If they would not allow me to speak there, I should speak at his house;
and the same man came and took us to his house,
where afterwards we had a pretty good meeting,
and such as had desires to hear the truth came there,
so that I had some very good service there for the Lord.

When we were free of that place we went to Worchum,
where we also had a meeting or meetings.
When we were pretty clear of those parts, we returned again for Amsterdam,
where we were received with joy and gladness by Friends,
who rejoiced with us in the good service which we had had;
and blessed be the Lord for our preservation.

[.emphasized]
+++[+++From this city William Caton addressed a letter to Friends in England,
(as is supposed,) from which the following extracts are selected.+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
William Caton to Friends in England

[.salutation]
O! My beloved friends,

It is delightful to me to meditate upon the Lord`'s love to you,
and it is a comfort and refreshment to my soul
to feel you in the unity of the eternal Spirit,
wherein I have daily communion with you, though I am necessitated,
for the scattered seed`'s sake, to be much as without the camp,
where the reproach is borne, with many weights and burdens,
by reason of which my soul is sometimes bowed down.
Yet, O! My friends, I share with you of that joy and peace, love and life,
which abound in your tents;
and therein can I rejoice with you in the midst of our trials and sufferings,
though as to the outward I am far separate from you.
Yet know, that I have no more lack and scarcity than I had when I was with you;
for my heart is filled with love, my mouth with praise, and mine eyes with tears,
when I behold your integrity and innocency, your faithfulness and constancy,
under your trials and burdens.
Often is my soul poured forth unto my Father on your behalf;--unto whom a child is born,
unto whom a Son is given; whose name is called the Prince of Peace,
and of the increase of whose government there shall be no end.
This is He, of whom I bear testimony to the nations, though they abhor Him,
and say within themselves,--'`we will not have Him to rule over us,
or we will not allow any of His messengers and servants to dwell among us,
but we will imprison them, and put them to death,`' etc.
Thus the Lord may permit them to do,
until they have filled up the measure of their iniquities, as the Amorites did;
and then shall his iron rod be stretched over them,
by which they shall be broken to pieces like a potter`'s vessel, who have abhorred Him,
and hated Him without a cause; but in that day will he spare you,
who have followed Him through great tribulation.-- In the meantime, O! Beloved,
he will try your faith and patience; but be you not therefore troubled,
for he knows what is good for you,
in whom he has chosen in these latter days to manifest his power and glory,
to the families of the earth,
whose glory and dignity must be stained and brought to nothing.

--

[.offset]
+++[+++He then proceeds to give a similar narrative of his labors in Friesland, etc.,
though somewhat more minute than given at this place in the Journal.
He afterwards adds;+++]+++

[.embedded-content-document.letter]
--

The sudden and violent storm which you have had in England,^
footnote:[See the [.book-title]#Histories of England# concerning the
troubles consequent upon the return of Charles II.]
has also stirred the waters very much here, so that they rage and swell,
as if they would prevail beyond the bounds which are set for them.
Much mire and dirt they cast up, venting part of it in their weekly intelligence,
and part in ballads,
wherein they seem to lay that chiefly to the charge of
Friends which lately happened in London,
as if they had conspired together to do much more than what was done.
The vulgar sort of people that have no feeling of the witness of God in themselves,
they believe it; but some sober and honest-hearted men slight it,
and do not much regard it.
But the baser sort take a mighty occasion hereby against us,
and they rage and tear as if they would swallow us up quickly.
We are credibly informed that fifty of the wildest of men here have combined together,
not only to break our meeting, but also to pull down the house to the ground,
where we have often met: so that you may understand,
that we are here daily in as great jeopardy as they in England,
that are not yet cast into prison.
The last first-day there were some very wicked men at our meeting,
who were exceedingly desperate and violent;
but blessed be the Lord! They were not permitted to do much harm,
and that which they did, was more to the house, than to Friends,
who are given up to the will of the Lord, as well to suffer with you for the Truth,
as to rejoice with you in the Truth.

Now friends, you know this day has been long foreseen,
and often have you been told that it would come, and seeing it is come,
think not these fiery trials strange which attend,
though for the present they may not seem joyous; yet without all controversy,
good will be brought forth by them to some, and these things shall not be in vain;
for it appears to me that they work together for the hastening of that work,
which the Lord is determined to cut short in righteousness for the elect`'s sake.
Therefore, let that reasoning part be kept under, that would say,
this would hinder the work: for who are you to reason with the Lord! Is not the work his?
And do you know better than he, what would be for the furtherance of it?
If not, be still, patient, and content; and let him work for his Truth with us,
or without us, according to the good pleasure of his Will; who has all power in his hand;
and this is he in whom we have believed, who commands the winds and the seas to be still,
and they obey him; have we not seen it, and are not we his witnesses?
If so, let us be patient a little, and we shall see the Lord work wonderfully.

Though I have written thus largely to you at present,
yet my heart is as full of love as it was when I began to set pen to paper:
so in the fulness, do I most dearly salute you, and in it do I leave you,
and commit you unto Him,
who is of power to establish all your hearts in the living Truth, in which I remain,
your dear brother in the fellowship of sufferings, in the gospel of peace,

[.signed-section-signature]
William Caton.

[.signed-section-context-close]
Amsterdam, 25th of Eleventh month, 1660.

--

I continued several months in Holland, where I had very good service,
sometimes at Atkmore, sometimes at Haarlem, sometimes at Leyden, sometimes at Rotterdam,
but mostly at Amsterdam; and I was much alone, especially about that time,
for William Ames who had had very good service in those parts, was some time in Germany,
and some time at Hamburgh: and once he travelled through Bohemia, and to Dantzic,
and from there to Poland.
John Higgins who had been much in Holland, was seldom with me;
so that I was much alone in the country:
but the mercy and goodness of the Lord abounded very much towards me,
for which my soul has cause forever to praise and magnify his name.

About the time called Whitsuntide, in the year 1661,
it was upon me to come over to London, chiefly to visit Friends there and thereabouts,
after their great suffering.
And the Lord gave me an opportunity, with two other Friends, namely: William Welch,
and Benjamin Furly.
Through the mercy of the Lord we got well over to Harwich, and from there to Colchester,
and so to London; where I was at several precious meetings,
and was more than a little refreshed with the brethren, not only at London,
but also at Kingston.
But being pretty much pressed in spirit to return for Holland again,
where there was some needful service for me, which required my haste,
I took my leave of Friends and brethren, in much love and unity at London,
with whom my refreshment at that time was so great,
that the remembrance of it afterwards was a great comfort to me.
We got well back to Colchester, where we had a very large and precious meeting,
to our own and Friends`' strength in the Lord.
We then went to Harwich, from which we passed over to Holland again,
and had a prosperous and successful journey of it, blessed be the Lord,
which tended much to our encouragement.

At that time I had in hand the book called [.book-title]#An Abridgement#,^
footnote:[An Abridgement or Compendious Commemoration of the remarkablest Chronologies
which are contained in that celebrated Ecclesiastical History of Eusebius,`" etc., 1661.
Reprinted 1689. Whiting`'s Catalogue.]
which I printed at Rotterdam; and after I had finished it,
I visited Friends in most places of that country,
and had several good meetings among them, to their and my refreshment in the Lord.

About that time it was upon me to go into Germany, partly to visit Friends,
and partly to speak with the Prince Palatine, and some else in that country,
I took my leave of Friends in Holland with much tenderness of heart,
committing them to the custody and protection of the Almighty.
About the 10th of the seventh month, 1661, with my dear brother William Ames,
I set forward on our journey towards Germany, and in due time we got well to Cologne;
from there we travelled towards the Grave de Whitt`'s country,
who had promised large liberty to all sorts of people,
that would come and inhabit in his dominion.
When we came there, we went to his house, and had an opportunity to speak with him;
and he reasoned very moderately with us a while,
and we endeavored to inform ourselves as much as we could from his own mouth,
of the certainty of what was published in his name concerning liberty.

But in the end, we perceived clearly from him, that his invitation,
though promising liberty or toleration,
was not so much out of love to tender consciences,
as out of covetousness for what was theirs, as since has more evidently appeared.

After we had had a very good time with him, and had informed ourselves sufficiently,
and tried the ground from which such things proceeded, we parted from him,
and went up into the country,
and had good opportunity to speak with some of the priests and people;
and after we had satisfied and cleared ourselves, we left those parts,
and travelled on our journey towards the Palz or Palatinate;
where in due time we arrived, through the mercy of the Lord, at a place called Kriesheim,
where we found a small remnant of Friends, that bore their testimony to the truth;
with whom we were refreshed, after our long and pretty tedious journey.
There we continued some time, helping them to gather their grapes,
it being the time of their vintage and when we had had a time of refreshment among them,
we travelled towards Heidleberg, the place of the prince`'s residence.

Soon after we came to Heidleberg, we went to the captain of the prince`'s life-guard,
and made known our desires to him concerning speaking with the prince;
and he was willing to procure us access to him.
Soon after, the prince sent for us to his palace, and he being at dinner,
caused us to stand by him; and withal he heard very moderately what we had to say to him.
Afterwards we presented several books to him, all which he kindly received from us,
and was very courteous to us,
and reasoned very familiarly with us in the
presence of the great ones that were with him;
and after we had had a favorable opportunity with him, we returned to our lodging.

In a short time after we went up to the prince`'s palace again,
having some further occasion to speak with him; and having free access to him,
we found him very moderate and courteous to us as before.
He spoke to his captain to cause us to sit down at the table with his attendants,
which we found freedom in the Lord to do; for he seemed to be somewhat troubled before,
when he had observed our unfreeness in that thing.
After dinner we had much private discourse with him,
the governor of Manheim only being present,
and we found him to be pretty courteously affected towards us;
and therefore we were the more free to declare the truth in much plainness to him,
and zealous in pleading Friends`' cause with him,
who had suffered by the priests about their tithe in his dominions.
After we had spent some hours with him that day, we returned to our lodging again.

About that time we were very busy in answering several books
that were still in existence in High Dutch against the truth and Friends;
the answers to which we intended to have printed here,
but the printers fearing the reproof of the clergy,
dared not print them for us in this city.
We then departed from there, and returned again to Friends at Kriesheim;
and when we had stayed some time with them,
William Ames determined to return again for Amsterdam,
there to get the aforesaid books printed.
He took his leave of Friends, and I went along with him to a place called Alstone,
where the governor of those parts lived.
It was upon us to go to him, to lay some abuses before him that were sustained by Friends.
He was moderate towards us, and a good service we had with him;
and he gave me an order for the officer of the place where Friends lived,
to take care that the rude multitude did not abuse Friends.

After we had been with him,
we took leave of each other in the endearedness of our Father`'s love,
and he +++[+++William Ames+++]+++
went for Holland, and I returned to Kriesheim again;
there I stayed with Friends some time, and afterwards went to Heidleberg again,
for I was not clear of that city.
When I came there I hired a lodging in a goldsmith`'s house,
and sometimes I went up to the prince`'s palace, and had good service there;
and sometimes I was with some of the great ones of the city,
with whom I had also very good service,
and some of them were very courteous and respectful to me:
and more love appeared in some of them towards me than others could well bear.
Then began the enmity in the clergy to get up against me;
and through the means of some that were envious against me, I with another young man,
who were all the Friends that were in that city,
were ordered to appear before the council, as also the man that entertained us.
This accordingly we did, and had a very good service,
for never had there been any Friend there before: so they had many things to query of me;
and the Lord was pleased at that very time to give me enough with which to answer them,
as also utterance, boldness, and dominion, even to the admiration of some.
They were moderate towards us,
and allowed me to speak pretty freely and largely among them; but in the end,
that they might appear to do something, they would have me to depart out of their city,
though they had nothing to lay to my charge, except for declaring the truth,
and dispersing some books which testified of the truth; nevertheless,
they allowed us then to depart from their judgment seat in peace.

Afterwards the prince came to hear of it, and as we were informed,
was very highly displeased with the council for troubling us,
when we had given them no just occasion.
After that I went to the president`'s house, who had examined me before the council;
and after a little discourse with him, he became pretty moderate,
and reasoned very familiarly with me,
and asked me many things concerning our Friends in England;
as also concerning the magistrates`' proceedings towards them;
and I was very free to give him a full account thereof for his information.
Before we parted he seemed to be very loving to me,
and thanked me for the present I had given him, which was some Friends`' books;
and yet before the council,
my giving of such books to people was the greatest crime they had to lay to my charge,
though both the prince and he received them from me, and accepted of them.
