== Chapter XV

[.chapter-synopsis]
* 1661+++.+++ He visits Manheim and Frankfort, his ill-treatment in a Monastery
* Visits the Jesuits`' College at Worms
* At Heidleberg is introduced to the Prince
* Is married to Anneken Derricks at Amsterdam, 1662.

I was several months, yes half a-year, in that country,
where I had very good service for the Lord, some time in one place, some time in another.
I was several times at a city called Manheim, where there were a sort of Baptists,
who lived together as one family, and had their goods common;
with whom I was several times, and did bear my testimony among them to the truth of God,
though few of them received it.
I was several times with the governor of that city at his own house;
and he was very courteous to me, at least seemingly,
and desired me as often as I came to the city, to come to his house.
I was also in the country with a countess, so called, who was very loving to me,
and pretty open to hear the truth; and at her house I found a great lord, so called,
who formerly had been general of the emperor`'s army, as I was informed;
and a great conference I had with him in the countess`' presence,
who was rather one with me in her judgment, than with the great man before mentioned;
and after I had had some very good service with them, I left them.

I was also at Frankfort, and endeavored to get some books printed there,
but could not prevail with the stationers; for the books that were to be printed there,
were first to be viewed by some of the clergy.
When I saw I could not prevail there, I went with a Friend to another city called Hannau,
where we got our business done; and afterwards returned again to Frankfort,
one of the chief, if not the chiefest, city in Germany.
On a certain time, I went into their chief monastery or temple,
where the emperors are usually crowned; and the priests were gathering to their devotion:
they were exceedingly offended with me,
because I did not stand uncovered in what they call sacred, though it be an idolatrous,
place.
Some of the priests spoke to me, and one especially was exceedingly angry;
and when we had spoken but a little together in Latin, he turned from me in a fury,
and another that was with him fell upon me, and beat me sorely,
and there he left me bleeding in the temple, where I left much of my blood behind me,
as a testimony against the idolatry of that idolatrous place.

I was also in the synagogue of the Jews of that city, where I reasoned much with them,
and had a good opportunity to bear a faithful testimony of the eternal truth;
though they could apprehend little to it with their dark minds,
which were blinded with the god of this world, as their forefathers were.
I had also some books to dispose of among them,
which for novelty`'s sake they coveted much after: and when I had cleared myself of them,
I left them; and in due time returned again into the Palz.

I was also at the city of Worms; and it was upon me to go to the Jesuits`' college,
to reason with them, or some of them, concerning the truth of God, and their traditions,
which I did.
When I came there, one that was eminent among them did soon enter into discourse with me,
and spoke very feignedly to me for some time; for at the first he seemed to have hopes,
as it appeared to me, to have won or gained me to his religion;
and therefore did he seem to be the more ready and
willing to resolve me in whatsoever I propounded,
so far as I believe he well could.

But when he saw I did notwithstanding lay open their apostasy,
and boldly gave my testimony against their inventions, superstitions, and traditions,
he could scarcely contain himself from breaking out into a passion,
I spent some hours in dispute with him,
in the presence of several that belonged to the college,
for whom he was as the mouth for the whole.
When I had cleared my conscience,
and borne a faithful testimony unto the truth among them, I left them,
and returned again to Kriesheim, where our Friends inhabited; for sometimes I was there,
sometimes at Heidleberg, and sometimes elsewhere,
where I saw the Lord had a service for me.

[.emphasized]
+++[+++The following is an extract from an Epistle addressed to Friends in London,
by William Caton, dated Kreisheim, near Worms, in Germany, 30th of Eleventh month, 1661.
This instructive Epistle is printed at large in [.book-title]#Besse`'s Sufferings#,
vol. 2. p, 451.+++]+++

[.embedded-content-document.epistle]
--

[.letter-heading]
William Caton to Friends in London

We have cause to praise and magnify the Lord God omnipotent forever,
who does not only comfort and refresh us in our tribulations,
through the consolations of his eternal Spirit, but also has prepared a refuge for us,
which we have truly found in his eternal light and pure power.
And now if no storm had come,
then I believe there would not have been such flocking and flying to this refuge,
as there has been, and as there is, and as I hope, there will be; therefore,
if the storms of persecution do drive such as were neither cold nor hot from under
their green trees of specious pretences and fair shows of religion and reformation,
to this sure hiding place or refuge, which is in the eternal light, life, and power,
which you have now made manifest, then will it be good in its season.
Therefore let none be afraid of it who are faithful in their measures;
for indeed our heavenly Father is so abundant in mercy and goodness to his people,
that if he suffers storms and tempests to arise, he does not only still them,
but even in the very time of them he covers his dear
babes with the banner of his everlasting love,
so that truly they need not to fear,
though sometimes they that are tender and young among them may be too much afraid.

And forasmuch as I know that the refuge before mentioned is known to you,
and the covering of the Lord`'s eternal Spirit manifested in you,
which is the banner of his love spread over you,
therefore I beseech you to be of good courage in the Lord:
for to what end should you fear?--to what end should you be troubled?
to what end should you take thought?
You know that neither fear of heart, trouble of mind, nor yet taking of thought,
can in any wise avert these things.

And if it be the good pleasure of the Almighty to purge
and refine you in the furnace of persecution,
as heretofore he has done with many of his witnesses in the world,
think it not strange that it should be so with you:
but rather think it strange that the Lord has so long dealt so gently with you,
and that he has so remarkably restrained the violence of the mighty,
who have risen up against you, as if they would have devoured you at once.

But behold, how have they been abased, brought down from their seats, and overturned;
and though they have, as it were, bruised your heel,
yet they have not prevailed against the Lamb, the captain of your salvation;
neither have they overcome you, whose faith has stood in the power of the Most High,
through which you have overcome, and not by the force of arms, nor by might of princes,
nor by the greatness of your multitude.
Remember, therefore, these things;
and strengthen you one another in the faith and in the patience;
and look you alone unto the Lord,
and hearken and hear what his Spirit says in you and to you.

When the spirit of enmity rules,
there is not much liberty to be enjoyed in matters of religion;
for it is well known to you, how through that spirit we have suffered from the beginning,
which has wrought mightily against us in our native country.
In these countries there are three sects tolerated, namely: the Roman Catholics,
the Lutherans, and the Calvinists;
and all these have their particular government in their particular cities and villages;
and all of them are addicted to persecute those that are not of their sect.
But above all others they seem to be bent against us, as the most offensive, irregular,
and perturbatious people that are of any sect;
and notwithstanding the great variance that is and has been among themselves,
yet they can, as it were, join hand in hand against the truth and us.
As for the Roman Catholics, they hate us as new up-started heretics,
whom they account worthy of death: and the Protestants, they revile us and upbraid us,
as if we were the pope`'s emissaries;
and many of them esteem us as not fit to live upon the earth:
so that as much as in them lies, they seek to toss us to and fro,
as a ship upon a troubled sea.
But thanks be to God, our anchor holds; so that they, with all their hard threatenings,
which proceed from their rocky hearts, cannot split our confidence,
nor make shipwreck of our faith; which is in the Lord Jehovah, who is over all,
blessed forevermore!`"

[.signed-section-signature]
William Caton.

--

When I was at Heidleberg, there came two of my dear brethren to the city,
John Stubbs and Henry Fell, who had been at Alexandria in Egypt, and in Italy, etc.
The postmaster of the place seeing them, did bring them to my lodging,
for he knew me well, for they had no knowledge of my being in the city; presently after,
came the captain of the prince`'s life-guard, having seen them in the street;
and he being a very courteous man to us, discoursed very friendly and familiarly with us,
and afterwards told the prince of the aforesaid Friends being in the city.
Soon after,
the prince sent his secretary to my lodging to desire
us to come up to the castle to speak with him,
which accordingly we did; and when we came there,
he began to speak friendly and familiarly to us, as his manner was,
and did ask them much concerning their travels, and how it had been with them, etc.
And a very great opportunity we had with him in the presence of the nobles, so called,
that were conversant with him.
After he had discoursed long with us, he parted very lovingly from us,
and soon after we went out of the city.

When the aforesaid brethren were with me, I received some letters out of Holland,
whereby I was informed of the death of Niesie Derricks, of Amstersdam,
who had been a dear and special friend of mine,
and a true and faithful servant to the flock of God in the Low Countries;
of whose love and virtue, faithfulness, and good service which she did in her day,
a volume might be written.
When I heard of her departure, my heart was much saddened, and broken within me;
and indeed it was more than I could well bear; but the aforesaid brethren being with me,
they bore with me; and the Lord supported me in that heaviness,
and comforted me with the promise and assurance which I had from him,
of his raising and bringing her sister Anneken Derricks, with some else, into her love,
life and spirit, to perform that or the like service for the Lord which she had done.

When I had been about half a year in Germany, and had had very good service,
especially in the Palatinate, it was upon me to return again for Holland,
which accordingly I did.
When, through the mercy of the Lord, I was gotten well there, I visited Friends,
as my manner was, and we were sweetly refreshed together.

[.offset]
+++[+++In the eighth month, 1662, he was married to Anneken Derricks,
at the meeting in Amstersdam.+++]+++

The same day after the meeting was done, we brought William Ames`'s body to the ground,
who had finished his testimony, and left a good savor behind him.
Though we went as wisely to work as we could to prevent a tumult;
yet nevertheless on a sudden the rude people were gathered together,
and became so tumultuous,
that not without much difficulty we could get through them with the corpse,
which finally was laid in the ground; and afterwards the multitude was very rude,
and Friends were much abused; howbeit, through mercy we were all preserved.
