== Chapter XVI

[.chapter-synopsis]
* 1662-- He returns to England; when in London, he sees Edward Burrough in Newgate shortly before his death
* Travels into Surrey, Sussex, and Kent; is apprehended at Folkestone, but is discharged
* Again visits Holland, and returns with his wife: travels into Warwickshire, etc., and arrives at Swarthmore.

After our marriage I continued several weeks with my dear wife,
and the Lord was pleased very much to comfort and refresh us together
with his infinite loving-kindness which abounded to us,
and with his heavenly blessings which he caused to descend upon us;
for which our souls have cause forever to praise and to magnify his name.
Afterwards I went out upon the service of truth, to visit Friends in other places,
as I had done before.

In less than three months after I married, it was upon me to go for England;
and in order thereunto I took leave of my dear wife and Friends in those parts;
and about the 25th of the eleventh month, 1662, I embarked for England;
and through the mercy of the Lord, I got well to Colchester,
where I was sweetly refreshed with Friends, as I usually was in that place.
Afterwards I went into the country, where I had several good and precious meetings,
and then went up to London with another dear brother,
and there I was also sweetly refreshed as I often was among the flock of God,
and especially at Newgate with dear Edward Burrough, who was then a prisoner there.
But in less than two weeks after he was released from his bonds,
for the Lord removed him out of this evil world,
that he might reward him with life everlasting in the world without end.

When I had been certain days in London, it was upon me to go down into Surrey, Sussex,
and Kent, which I did, and visited Friends in Surrey,
and had some very good meetings among them, to our refreshment in the Lord,
being accompanied by my dear brother Joseph Fuce.
Afterwards we went to Horsham in Sussex,
and visited our Friends and brethren who were in prison there;
after which we had some good meetings in that county.
At a meeting at Hurst,
I was in much danger of being apprehended through the envy of a wicked priest;
but the Lord restrained the officers from executing his will,
and therefore I was preserved out of their hands.

We passed into Kent, visiting Friends and their meetings in our travels,
as our manner was: at Staplehurst we had a precious general meeting,
after which we parted in the fulness of brotherly love; he +++[+++Joseph Fuce+++]+++
went back into Sussex again, and I went towards Dover.
When I came to Foulstone +++[+++Folkestone+++]+++
I attended a general meeting there; and the officers of the town, while I was speaking,
came into the meeting, and apprehended me, and carried me before the mayor,
who being pretty moderate, would finally have set me at liberty, if I would promise him,
that if I went to the meeting again, I would speak no more in it,
which thing I could not in any wise promise, and gave him my reasons why I could not;
upon which he sent me to prison.

That same day afterwards we were brought twice before the mayor, there being others with me,
who finally discharged us all that night.
I took leave of Friends there, it being the 1st day of the first month, 1663,
and went to Dover, where I had a very good,
serviceable and refreshing meeting among Friends and
being comforted together in the presence of the Lord,
I left them, and went to a general meeting in East Kent, and from there to Canterbury,
and so to Rochester, visiting Friends, and from there to London.
I stayed several days in that city, where I had several precious meetings:
and afterwards, according as it was upon me, I went from there into the country again,
in order to return for Holland;
and had several good meetings in the country at my return,
to the renewal of our strength in the Lord.

When the Lord of his mercy had thus prospered my journey, and made it successful,
he also gave me a good opportunity to return again for Holland;
where I arrived about the 10th of the second month, 1663,
to my own, and Friends in that country, great refreshment, and especially of my dear wife;
with whom I stayed not very long at her habitation, but as was upon me,
went from city to city, visiting Friends and their meetings: and the Lord was with me,
in whose living presence we were comforted together as in months past.

I had not stayed above three months in those parts,
when it was upon me to go for England again.
My dear wife having longing desires, with some other Friends at Amsterdam,
to see Friends in England; she and they determined to go along with me,
which accordingly they did;
and through the good hand of the Lord we got to
Harwich about the 29th of the fourth month 1663,
where we had a very good meeting with Friends, to our refreshment.
From there we went to Colchester, where we also had a good meeting.

On the first-day following, we were at a general meeting in the country,
to which many Friends and others resorted;
and when I came there I understood that the constable had been there before me,
and that he was determined to come again to break up the meeting.
However, when Friends were gathered,
I went in among them in the name and power of the Lord;
and when I had sat but a little in the meeting, my heart was full of the Word of life,
which I had to communicate to the congregation,
and a very living and precious meeting it was.
When I was done speaking, and was sitting down, the constable came into the meeting,
with his warrant subscribed by several justices; but he knew not me from the rest.
Moreover, there being a woman Friend speaking, he troubled himself a little with her;
but afterwards went away, and my liberty was preserved for future service,
through the mercy and goodness of the Lord God.
Afterwards we visited Friends at Coxhall +++[+++Coggeshall+++]+++
and Witham, to their and our refreshment in the Lord.

In some short time after, we went up to London,
where we were much comforted with Friends;
who rejoiced more than a little to see people of another nation,
and of a strange language,
brought into the same living truth in which they were established,
and to bear the same image that they bore, and to be comprehended in the same love,
which the Father of our Lord Jesus Christ had shed abroad so richly among them.
And when we had been very sweetly refreshed with Friends in
several precious meetings in the city and elsewhere,
we went to Kingston to a general meeting;
and one of the Dutch Friends was moved to speak pretty much in the meeting,
and I interpreted for her: with which Friends were much affected and refreshed,
feeling the same life and power in her that dwelt in us,
giving testimony to the same eternal Truth; this, I say, did much refresh Friends,
and confirm them in the present truth.

After that we returned to London, where we were comforted together as before;
but we stayed not long there, for it was upon me to go into the north;
and it was upon my dear wife, and the rest of Friends, to return again for Holland.
I with several dear Friends, accompanied them aboard, where I took my leave of them,
and committed them to the custody and protection of the Almighty.

In a short time after I also took my leave of Friends in the city,
and pursued my journey northwards; and when I came into Warwickshire,
I met with my dear friend Margaret Fell, and two of her dear children,
and also two dear brethren, Thomas Salthouse, and Leonard Fell;
and truly our rejoicing was more than a little in the Lord,
having not seen one another for a long time before.
We travelled together into Staffordshire, and there parted, some went for the north,
some for Derbyshire; I returned again to a general meeting in Warwickshire,
and went afterwards to Warwick, Coventry, etc.,
and visited Friends in several places in that county,
where I also met with dear George Fox to my refreshment.

After that I went into Derbyshire, and had a meeting in the city of Derby,
and visited Friends elsewhere in that county.
Then I went into some part of Nottinghamshire, where I met with dear Margaret Fell again;
and afterwards we went to Chesterfield, where we had a very good meeting.
We then went into Yorkshire, visiting Friends as we went,
to a place called Sinderhill Green, where dear George Fox met us:
and there we had a splendid general meeting together.

Afterwards we went to Balby, where we stayed some days, and many Friends resorted there,
so that we had a good time of refreshment together.
After this I took my leave of Friends,
for it was upon me to hasten towards Swarthmore in Lancashire, which I did,
but visited Friends by the way as my manner was, to our mutual comfort in the Lord.
In due time, through the goodness of the Lord, I got well to Swarthmore,
where I had not been for some years; and there I was received in abundance of love,
and was very sweetly refreshed with the remainder of the family.
When first-day came, we had a very precious meeting,
to the refreshing of the whole body of Friends that were present;
for the power and presence of the Lord God was much among us,
which was the cause of our great consolation in the Lord:
blessed be his name forever and ever.
